### ISSUE TITLE
The ara_api and ara_frontend Ansible roles should support deploying to EL8

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#107]
## What component is this about ?

The ara_api and ara_frontend Ansible roles

## What is the idea ?

We currently support deploying the API server to Fedora and Ubuntu.
Since EL8 now ships with Python 3 and CentOS 8 is readily available, we can consider adding support for it.

**Comment by arrfab** [comment]
+1 and happy to test this when it's ready as myself had to use pip + virtualenv for this on centos8 :-)

**Comment by dmsimard** [comment]
This is WIP in https://review.opendev.org/#/c/702996/

There's an issue in the postgresql integration test because installing docker on centos8 fails. I'll look into it but it has otherwise been tested successfully: https://47d287368a919a1c4cf3-4c4b5a0c8f32c7447091aeee05f8c4bc.ssl.cf1.rackcdn.com/702996/2/check/ansible-role-ara-api-centos8-2.9/17aa3f5/logs/static/

**Comment by dmsimard** [comment]
Support for deploying on EL8 with the Ansible roles has landed in https://github.com/ansible-community/ara/commit/867c4232226750f3d1f464de08aa88099446c620
