### ISSUE TITLE
Ara Api server UI gives response timedout(504) 

### ISSUE THREAD

**Issue by saranyasridharan** [ansible-community/ara#109]
## What component is this about ?
Ara API server 

What is your ARA installation like ?
I have installed Ara1.1 , with pip install inside a virtual environment
Ansible 2.9,psql (9.2.24, server 11.5)

 What is happening ?
Ara UI is loading very slow , it gives 504 timed out error, Some time I get 'too many opened files' other times  I dont see any error in the nohup output and server side its giving 200 response, but in UI it is timing out. I am attached the db data details

![image](https://user-images.githubusercontent.com/15728811/72968359-4e62e600-3de9-11ea-8402-33ea78ad1a67.png)
I had this issue with sqlite, thought its db issue. Now I have changed to postgresql and migrated the old data to it. again I am getting the same error. After restart, it is better for sometime and the problem occurs again in few minutes. our setup is in aws environment , ara in one server and postgres in rds but having it in same setup also had this issue when the playbook is more than 300. this is server nohup output at that time of the issue.
![image](https://user-images.githubusercontent.com/15728811/72969444-7ce1c080-3deb-11ea-81f7-ca6a8cce539e.png)

What should be happening ?
UI should load irrespective of db load.

**Comment by dmsimard** [comment]
Hi @saranyasridharan and thanks for the report.

Could you look at your [DATABASE_CONN_MAX_AGE](https://ara.readthedocs.io/en/latest/api-configuration.html#ara-database-conn-max-age) setting ? It currently defaults to 0 which is not very appropriate for postgre. You can pick any number you are comfortable with, 60 is probably a good value to start with.

Also, I suspect that the current lack of pagination on the playbook report list is not helping in terms of performance.

**Comment by dmsimard** [comment]
Also, I see you mentioned ARA 1.1. Please make sure you are using the latest release which is 1.3.2 at this time.

**Comment by saranyasridharan** [comment]
Thanks for the response.Im running api internal development server(run
server) for high load, should I change that Apache production server to
reduce the delay ?

**Comment by dmsimard** [comment]
@saranyasridharan yes, you can expect performance improvements by running with an actual WSGI application server and a web server in front.

We have an Ansible role for the API server but it doesn't have an Apache+mod_wsgi implementation yet.

It does have an implementation with gunicorn and nginx which could help point you in the right direction, though. It's how the [live demo](https://api.demo.recordsansible.org) is currently deployed.

You can see what the playbook for the live demo looks like [here](https://github.com/ansible-community/ara-infra/blob/master/playbooks/live-demo.yaml) and the roles are in this repository: https://github.com/ansible-community/ara/tree/master/roles

**Comment by saranyasridharan** [comment]
Thanks @dmsimard . Does nginx and gunicorn support huge production load ? or Can I set the Apache + mod_wsgi like the regular way like we do in Django framework ?

**Comment by saranyasridharan** [comment]
> Hi @saranyasridharan and thanks for the report.
> 
> Could you look at your [DATABASE_CONN_MAX_AGE](https://ara.readthedocs.io/en/latest/api-configuration.html#ara-database-conn-max-age) setting ? It currently defaults to 0 which is not very appropriate for postgre. You can pick any number you are comfortable with, 60 is probably a good value to start with.
> 
> Also, I suspect that the current lack of pagination on the playbook report list is not helping in terms of performance.
> 
> Edit: I've created an issue about the lack of pagination here: #110

I have checked the setting. it was 0 as you doubted. I have changed that to 60, still the issue exists.

**Comment by dmsimard** [comment]
> Thanks @dmsimard . Does nginx and gunicorn support huge production load ? or Can I set the Apache + mod_wsgi like the regular way like we do in Django framework ?

@saranyasridharan Could you define what a "huge production load" is for you ?

I haven't benchmarked nginx/gunicorn and Apache/mod_wsgi for hosting the API server but either would provide improved performance over the embedded development web server.

I think the API server is a fairly standard django/django-rest-framework application and if you're used to hosting that in Apache/mod_wsgi, it should "just work". If it doesn't, please create an issue and we can look into it.

**Comment by dmsimard** [comment]
> I have checked the setting. it was 0 as you doubted. I have changed that to 60, still the issue exists.

@saranyasridharan Would you be wiling to try a patch that implements pagination on the playbook report list and let me know if it helps ?

You can see the patch [here](https://review.opendev.org/#/c/704181/) and it looks like this at the top right:
![Screenshot from 2020-01-24 12-45-07](https://user-images.githubusercontent.com/1291204/73092940-8a5e7f80-3eab-11ea-876d-b2b3182c64f9.png)


Here's an example of how you can install ara from source with the patch:
```
python3 -m venv /tmp/venv
git clone https://github.com/ansible-community/ara
cd ara
git fetch https://review.opendev.org/recordsansible/ara refs/changes/81/704181/3 && git checkout FETCH_HEAD
/tmp/venv/bin/pip install .[server]
```

**Comment by saranyasridharan** [comment]
sure that would be great. I can give it a try.

**Comment by saranyasridharan** [comment]
Thanks @dmsimard. we have deployed nginx & gunicorn hosting for now. we
will monitor the performance of that, if its not upto the expectation, I
will create a ticket for that.

**Comment by dmsimard** [comment]
@saranyasridharan is the performance better with nginx and gunicorn ? have you tried the pagination patch ?

**Comment by dmsimard** [comment]
@saranyasridharan the pagination patch has merged in master and will be released with ARA 1.4. I'll close this issue for now, please feel free to respond or create a new issue if there's anything.

**Comment by saranyasridharan** [comment]
Performance is improved now with the nginx and gunicorn hosting. we have
parked the pagination patch step, if this hosting doesnot solve our problem
, we will go to this. Thanks David or I will update next release directly.
Thanks for the support.

**Comment by saranyasridharan** [comment]
What is the release date of Ara 1.4?

**Comment by dmsimard** [comment]
> What is the release date of Ara 1.4?

@saranyasridharan there's no set date yet but I'm hoping for next week.

**Comment by saranyasridharan** [comment]
That's great. Thank you David.

**Comment by saranyasridharan** [comment]
@David Is there any update on the ARA 1.4 release date ?
