### ISSUE TITLE
Dockerfile for recordsansible/ara-api

### ISSUE THREAD

**Issue by markfaine** [ansible-community/ara#132]
## What component is this about ?
The docker image for ara-api

## What is your ARA installation like ?
I'm working on a deployment with swarm as a stack with mysql.

## What is the idea ?
I know you use buildah but I could really use a Dockerfile so that I can see what it is you're doing in your build and modify accordingly for my own.  I'm building swarm files (compose files) and it helps a ton if I have a reference.

I'm not sure yet if I will have a separate UI and API container yet but it is likely.

Thanks!

**Comment by dmsimard** [comment]
Hi @markfaine !

We don't maintain a Dockerfile but it should be possible to create one of your own based on the scripts used to build the images like this one: https://github.com/ansible-community/ara/blob/master/contrib/container-images/fedora-pypi.sh

So, roughly speaking:
1) Start from an image where python3 is available
2) In your case, install mysqlclient (not PyMySQL!) library, on Fedora/EL this is python3-mysql
3) Install pip
4) Install ara[server], maybe with something like gunicorn or uwsgi to actually run the server
5) Set up a volume so settings and logs can persist

You would probably want to set up a web server in front for caching static assets or doing SSL termination. You can see for example the nginx configuration for the demo website here: https://github.com/ansible-community/ara-infra/blob/master/playbooks/templates/api.demo.recordsansible.org.conf.j2

I don't recommend using ara-web at this time, it's lacking in features and polish.

Let me know if you have any questions, happy to help.

**Comment by markfaine** [comment]
Thanks!

**Comment by markfaine** [comment]
Can you please explain to me what has changed?  I have been working on another project and am now returning to ARA after a brief absence and it seems that there have been some significant changes and I have to admit that I am a bit confused.  

Previously, I had configured ARA with a settings.yml file installed into ~/.ara/server/settings.yml.  This file is no longer needed?  I also am seeing there are some env variables that no longer are referenced in the documentation, such as "ARA_ADMIN_USER" and "ARA_ADMIN_PASSWORD".  Also, you referenced using something like gunicorn above, is this a new requirement, I did not do this before and yet there was an included web interface.  

I guess what I need to know at a minimum could be summarized as the following:  If I extend your docker image, (from: recordsansible/ara) and wish to have a web interface and use mysql as the backend database, what additional will need to be added to your image?  

Thanks, and sorry for the confusion.

**Comment by dmsimard** [comment]
> Can you please explain to me what has changed? I have been working on another project and am now returning to ARA after a brief absence and it seems that there have been some significant changes and I have to admit that I am a bit confused.

Happy to have you back :)

Maybe the changelogs could help ? We can probably do a better job at linking to them:

- 1.2: https://ara.recordsansible.org/blog/2019/11/06/announcing-the-release-of-ara-records-ansible-1.2/
- 1.3: https://ara.recordsansible.org/blog/2019/12/03/announcing-the-release-of-ara-records-ansible-1.3/
- 1.4: https://ara.recordsansible.org/blog/2020/04/15/announcing-the-upcoming-release-of-ara-1.4.0/

> Previously, I had configured ARA with a settings.yml file installed into ~/.ara/server/settings.yml. This file is no longer needed? 

``~/.ara/server/settings.yaml`` is the default location where the API server will retrieve it's settings, if this file doesn't exist, it will create a default one and use that. These settings can be individually overriden for the most part with environment variables -- you can see what settings are available in the docs: https://ara.readthedocs.io/en/latest/api-configuration.html.

> I also am seeing there are some env variables that no longer are referenced in the documentation, such as "ARA_ADMIN_USER" and "ARA_ADMIN_PASSWORD".

I could be mistaken but I don't recall the project making use of these variables, maybe it was a local implementation ? The django backend provides user management and you can find docs about it here: https://ara.readthedocs.io/en/latest/api-security.html#user-management

> Also, you referenced using something like gunicorn above, is this a new requirement, I did not do this before and yet there was an included web interface.

gunicorn is not required but the development web server included by django isn't meant for production use -- as in, it'll work fine on your laptop but if you're going to be throwing any kind of volume at it, you'll want something more performant.

gunicorn is a WSGI application server which is meant to run python applications but there's nothing preventing you from running it with other application servers like Apache mod_wsgi or uwsgi.

> I guess what I need to know at a minimum could be summarized as the following: If I extend your docker image, (from: recordsansible/ara) and wish to have a web interface and use mysql as the backend database, what additional will need to be added to your image?

The images the project produces ship with the MySQL client package installed by default: https://github.com/ansible-community/ara/blob/fd03b4cc557d0f952dd0e05f7c0a34f5a36857d5/contrib/container-images/fedora-pypi.sh#L5-L9

You'll need to configure the server to connect to it by modifying your settings.yaml to something like this:
```
  DATABASE_CONN_MAX_AGE: 180
  DATABASE_ENGINE: django.db.backends.mysql
  DATABASE_HOST: 127.0.0.1
  DATABASE_NAME: ara
  DATABASE_PASSWORD: password
  DATABASE_PORT: 3306
  DATABASE_USER: ara
```

It also includes a built-in reporting interface like this one: https://api.demo.recordsansible.org/

**Comment by markfaine** [comment]
Do you recommend running the container as root or creating a ara user and a virtualenv?

**Comment by dmsimard** [comment]
@markfaine I don't have a particular recommendation, I think your personal preference in terms of installation/deployment/upgrade workflow has more importance, either will work the same.

**Comment by dmsimard** [comment]
@markfaine I'm tidying up issues and I'll close this one since I think you're in the right direction. Feel free to open another if there's anything.
