### ISSUE TITLE
Missing pbr dependency on Fedora and EL packaging

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#140]
## What component is this about ?

Packaging for ARA on Fedora and EL

## What is happening ?

pbr is listed as a buildrequires but not as a requires in the packaging: https://src.fedoraproject.org/rpms/ara/blob/f32/f/ara.spec

This can lead to runtime exceptions on missing pbr if it has not been installed through other dependencies.

## What should be happening ?

pbr is a dependency and should be required.

**Comment by dmsimard** [comment]
@arrfab ^ FYI, are you building from the epel8 branch ? I will take care of this while bumping the packaging for the new 1.4.1 release.

**Comment by arrfab** [comment]
Yes, I wanted to open a PR to add it, as myself I discovered that it was needed at runtime.

**Comment by dmsimard** [comment]
Pull requests for 1.4.1 and adding pbr:
- f32: https://src.fedoraproject.org/rpms/ara/pull-request/4
- f31: https://src.fedoraproject.org/rpms/ara/pull-request/5
- epel8: https://src.fedoraproject.org/rpms/ara/pull-request/6

Haven't done master yet, I think it's failing to build because of the requires on python3-ara which hasn't been built yet.
The intent is to have "aliases" for ``ara`` -> ``python3-ara`` and ``ara-server`` for ``python3-ara-server`` in order to be able to do ``dnf install ara ara-server`` but I probably screwed that up.

**Comment by dmsimard** [comment]
f32, f31 and epel8 PRs are merged and updates submitted to bodhi.

**Comment by arrfab** [comment]
Good, submitted a build that I'll tag to testing too for CentOS (https://cbs.centos.org/koji/taskinfo?taskID=1329140) and if that works, I'll tag to -release and it will be signed and pushed to mirrors

**Comment by arrfab** [comment]
Correctly triggering now the python3-pbr install, so for centos configmanagement, I'll tag it to -release :
```
yum update  --enablerepo=centos-ansible-29-testing
Last metadata expiration check: 0:00:17 ago on Tue 02 Jun 2020 07:00:46 UTC.
Dependencies resolved.
=======================================================================================================================
 Package                  Architecture        Version                     Repository                              Size
=======================================================================================================================
Upgrading:
 ara                      noarch              1.4.1-1.el8                 centos-ansible-29-testing               22 k
 python3-ara              noarch              1.4.1-1.el8                 centos-ansible-29-testing              391 k
Installing dependencies:
 python3-pbr              noarch              5.4.3-2.el8                 centos-ansible-29                       90 k

```

**Comment by dmsimard** [comment]
@arrfab amazing! Thanks for taking care of this so quickly :tada:

I guess I'll close this issue now.
