### ISSUE TITLE
Environment variable for api_server

### ISSUE THREAD

**Issue by markfaine** [ansible-community/ara#184]
In the ansible.cfg in the ara section there is:
api_server = http://api.example.org
Can this be set with an environment variable?  I have a situation where the value isn't static or always known in advance.  ARA is running in a docker swarm and apparently 
http://tasks.ara_ara:8000 is not allowed.

**Comment by flowerysong** [comment]
The available configuration settings and corresponding environment variables are documented at https://ara.readthedocs.io/en/latest/ansible-plugins-and-use-cases.html#ara-default-callback-recording-playbooks-from-ansible

**Comment by markfaine** [comment]
> 
> 
> The available configuration settings and corresponding environment variables are documented at https://ara.readthedocs.io/en/latest/ansible-plugins-and-use-cases.html#ara-default-callback-recording-playbooks-from-ansible
Yes, I know. I looked.  That's why I'm submitting the issue.  I didn't see anything.

**Comment by markfaine** [comment]
Sorry, I think this is a different information.
