### ISSUE TITLE
Archive records

### ISSUE THREAD

**Issue by markfaine** [ansible-community/ara#194]
Not really sure if this is a feature request or if it already exists.  I'd like to be able to archive records so that they are still there and can be seen if "archived" is selected, however, they don't show up in the listing of playbook records by default.  This way I can schedule archival of records after so many days and then deletion of the archived records after another period of time.

**Comment by dmsimard** [comment]
Hi @markfaine, we don't currently have an implementation of what I'd call a "soft delete" but you might be interested in the ``ara playbook prune`` command: https://ara.readthedocs.io/en/latest/cli.html#ara-playbook-prune

You can use it to delete playbooks that meet certain criteria -- such as their age, for example to delete playbooks after 30 days:
``ara playbook prune --days 30 --confirm``

**Comment by markfaine** [comment]
Thanks I did find that and was able to use it.
