### ISSUE TITLE
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'playbooks.controller' in 'field list'")

### ISSUE THREAD

**Issue by markfaine** [ansible-community/ara#199]
I just rebuilt my docker container and picked up 1.5.4 in the process so I think it's likely that this has something to do with the upgrade?  Did the database schema change?

**Comment by dmsimard** [comment]
Hey @markfaine, you're right, 1.5.4 adds a new SQL migration and it needs to be run at least once with ``ara-manage migrate``.

You can see "Upgrade notes" at the bottom of the release notes: https://github.com/ansible-community/ara/releases/tag/1.5.4

**Comment by markfaine** [comment]
Thanks!
