### ISSUE TITLE
Column sorts empty the filter.

### ISSUE THREAD

**Issue by ylmrx** [ansible-community/ara#201]
## What is the issue ?

(webui, archlinux, python 3.8.5, ansible 2.10, ara 1.5.4, installed using pip, in a cpython3 based venv, 
the bug should reproduce within any sort of py environment though.)

Run a playbook on a bunch of boxes.
Pick one host in hosts section.
The playbook task are listed sorted from newest to oldest (unlike your console)
The playbook taks are now listed from oldest to newest, but with all boxes (filter was cleared)

## What should be happening ?

The filter should remain in place when switching a column-sort

**Comment by dmsimard** [comment]
@ylmrx o/ thanks for the issue!

I am aware of this and it needs fixing, it's been on my radar but haven't had time yet.

**Comment by dmsimard** [comment]
@ylmrx I had to experiment a bit to figure out the right way to do it but I think it works now.

I've proposed a patch: https://review.opendev.org/c/recordsansible/ara/+/773077 and it's currently deployed to https://demo.recordsansible.org/.

Would you like to try it out and let me know if it works for you ?

Thanks !

**Comment by ylmrx** [comment]
OK, I didn't notice the playbooks page was broken too :) 
So now the playbooks page is fine.
But I still reproduce the issue in the "play/task" view (ie. when you click a path on playbooks page)

**Comment by dmsimard** [comment]
The fix landed and will be released in 1.5.5, 1.5.5rc1 has already been tagged: https://github.com/ansible-community/ara/releases/tag/1.5.5rc1
