### ISSUE TITLE
Ara doesnt work with external postgres sql DB

### ISSUE THREAD

**Issue by kalyanbhonagiri16** [ansible-community/ara#203]
Just wanted to start with saying ARA is a great tool and help me automate my ansible output using ARA API's

## What is the issue ?
I have been trying to use postgres externalDB with ARA and ARA still takes sqllite.

This is how i created postgres:
docker run -d --name postgres-13 -p 5432:5432  -e POSTGRES_PASSWORD=ara -e POSTGRES_DB=ara -e POSTGRES_USER=ara -e PGDATA=/var/lib/postgresql/data/pgdata -v /mnt/cloudops_data/postgres:/var/lib/postgresql/data:rw --user $(id -u):$(id -g) postgres:latest

my ARA installation:
docker run -d -p 8005:8000 -e ARA_DATABASE=postgresql+psycopg2://ara:ara@qnc-cloudops-05:5432/ara docker.io/recordsansible/ara-api:latest

I tried changing settings.yaml with postgres DB changes but that didnt work either. Any help here would be greatly appreciated

## What should be happening ?
ARA should be taking postgres as its DB but this isn't happening.

**Comment by dmsimard** [comment]
Hi @kalyanbhonagiri16,

From looking at the specific command you pasted, it seems like you are not mounting a volume for the ara settings directory.
The dockerhub README provides the following commands:
```
# create a directory for settings and the sqlite database
mkdir -p ~/.ara/server

# with docker:
docker run --name ara --detach --tty \
  --volume ~/.ara/server:/opt/ara:z -p 8000:8000 \
  docker.io/recordsansible/ara-api:latest
```

While you won't be using sqlite, the volume is still important because you want to edit ``~/.ara/server/settings.yaml`` on your host and then restart the container so the new settings are loaded.

Let me know if that fixes it.

Thanks !

**Comment by dmsimard** [comment]
Oh, I gave that another read and this is wrong as well: ``-e ARA_DATABASE=postgresql+psycopg2://ara:ara@qnc-cloudops-05:5432/ara``.

This is not how you would pass the database information over environment variables.
I recommend using the ``settings.yaml`` file but if you really must use environment variables, have a look at the [API server configuration variables documentation](https://ara.readthedocs.io/en/latest/api-configuration.html).

At a minimum, you'd need to set the following variables:

- ``ARA_DATABASE_ENGINE``
- ``ARA_DATABASE_USERNAME``
- ``ARA_DATABASE_PASSWORD``
- ``ARA_DATABASE_HOST``
- ``ARA_DATABASE_PORT``

And with postgresql I also recommend setting ``ARA_DATABASE_CONN_MAX_AGE`` to a non-zero value so you can benefit from persistent database connections.

**Comment by kalyanbhonagiri16** [comment]
@dmsimard  
Thanks for the quick response.
Apologies i added wrong docker command for ara. I mount NFS volume, this is my command 
docker run -d -p 8005:8000 -v -v /mnt/cloudops_data/ara:/opt/ara:z -e ARA_DATABASE=postgresql+psycopg2://ara:ara@qnc-cloudops-05:5432/ara docker.io/recordsansible/ara-api:latest

I have also changed settings.yaml but looks like i haven't had ARA in my env variables. Will add them and let you know

**Comment by kalyanbhonagiri16** [comment]
@dmsimard  Tried with environmental variables, interestingly postgres complains about sqlite


docker run -d -p 8005:8000 -e ARA_DATABASE_ENGINE="django.db.backends.postgresql" -e ARA_DATABASE_CONN_MAX_AGE=300 -e ARA_DATABASE_USER=ara -e ARA_DATABASE_PASSWORD=ara -e ARA_DATABASE_HOST=<host> -e ARA_DATABASE_PORT=5432 -v /mnt/cloudops_data/new_ara:/opt/ara:z


# docker logs 2a8853fc5661
[ara] No setting found for SECRET_KEY. Generating a random key...
[ara] Using settings file: /opt/ara/settings.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/lib64/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "/opt/ara/ansible.sqlite" does not exist


The above exception was the direct cause of the following exception:

**Comment by dmsimard** [comment]
@kalyanbhonagiri16 you need to specify ``ARA_DATABASE_NAME`` too, I thought I had mentioned it in my last reply but apparently forgot.

**Comment by kalyanbhonagiri16** [comment]
Thanks David. Its work now. Appreciate all your help. closing the issue
