### ISSUE TITLE
How to find older docker image versions for ARA

### ISSUE THREAD

**Issue by kalyanbhonagiri16** [ansible-community/ara#204]
## What is the issue ?
How to find older docker image versions for ARA. I can only pull latest from dockerhub

**Comment by dmsimard** [comment]
Hi @kalyanbhonagiri16,

While the project tests and publishes updated images on a regular basis, we do not support or maintain historical tags other than ``latest`` at this time.

You're encouraged to build and customize your own images tailored to your needs and can find the documentation to get started here: https://ara.readthedocs.io/en/latest/container-images.html

I'll close this issue but can help point you in the right direction if you encounter problems with the build process.

Thanks !
