### ISSUE TITLE
Failed to get on /api/v1/plays: {'params': {'order': '-started', 'limit': 50}}

### ISSUE THREAD

**Issue by Rabieezz** [ansible-community/ara#215]
## What is the issue ?
The api doesn't seem to be working properly, the env variables are well loaded the surver is running but it doesn't store the records and when I run the following command it looks like the api fails to get on the plays, I am using the latest version could you please give some insight about this issue ?
```bash
~/.local/lib/python3.8/site-packages/django/bin # ara play list -vvvv
initialize_app
found extension EntryPoint(name='csv', value='cliff.formatters.commaseparated:CSVLister', group='cliff.formatter.list')
found extension EntryPoint(name='json', value='cliff.formatters.json_format:JSONFormatter', group='cliff.formatter.list')
found extension EntryPoint(name='table', value='cliff.formatters.table:TableFormatter', group='cliff.formatter.list')
found extension EntryPoint(name='value', value='cliff.formatters.value:ValueFormatter', group='cliff.formatter.list')
found extension EntryPoint(name='yaml', value='cliff.formatters.yaml_format:YAMLFormatter', group='cliff.formatter.list')
prepare_to_run_command: PlayList
Starting new HTTP connection (1): [proxyIP]:8080
http://[proxy IP]:8080 "GET http://127.0.0.1:8000/api/v1/plays?order=-started&limit=50 HTTP/1.1" 403 3749
HTTP 403: get on /api/v1/plays
Failed to get on /api/v1/plays: {'params': {'order': '-started', 'limit': 50}}
Expecting value: line 1 column 1 (char 0)
clean_up PlayList
got an error: Expecting value: line 1 column 1 (char 0)
```

## What should be happening ?
It sould show at least an empty table.

**Comment by dmsimard** [comment]
Hi @Rabieezz,

The error seems to be a HTTP 403 (Forbidden) which hints at an authentication problem.

Do you have authentication enabled with something like ``ARA_READ_LOGIN_REQUIRED`` or ``ARA_EXTERNAL_AUTH`` ?
Are you able to access the server interface from your browser ?

**Comment by Rabieezz** [comment]
Hi @dmsimard,
I did not activate authentication on ARA the` ARA_READ_LOGIN_REQUIRED` and `ARA_EXTERNAL_AUTH` are not loaded or activated anywhere.
I access to the server from the browser without authentication

**Comment by Rabieezz** [comment]
Hi again @dmsimard 
I just want to add that when I try to access from the browser to `http://127.0.0.1:8000/api/v1/plays` it is accessible and I can see the REST API form :

![image](https://user-images.githubusercontent.com/7777969/110810807-6d8b3400-8286-11eb-8830-14d52e9a13ab.png)

so I really don't understand why the error pops up when I try to acces from the cli. As I said before the authentication is not enabled so far.

**Comment by dmsimard** [comment]
@Rabieezz ara doesn't set up a proxy and I'm not familiar with the implications of going through a proxy for sending data to ara or receiving it. Are there any logs available at the proxy level that could hint you at the issue ?

**Comment by Rabieezz** [comment]
Hi @dmsimard,

well the culprit was the proxy because when I unset it ara works fine I can see my playbook and all the errors disappear so yeah when you try to use ARA make sure that the POST and the GET doesn't get blocked by the proxy.:

```yaml

~ # ara play list -vvv
initialize_app
found extension EntryPoint(name='csv', value='cliff.formatters.commaseparated:CSVLister', group='cliff.formatter.list')
found extension EntryPoint(name='json', value='cliff.formatters.json_format:JSONFormatter', group='cliff.formatter.list')
found extension EntryPoint(name='table', value='cliff.formatters.table:TableFormatter', group='cliff.formatter.list')
found extension EntryPoint(name='value', value='cliff.formatters.value:ValueFormatter', group='cliff.formatter.list')
found extension EntryPoint(name='yaml', value='cliff.formatters.yaml_format:YAMLFormatter', group='cliff.formatter.list')
prepare_to_run_command: PlayList
Starting new HTTP connection (1): 127.0.0.1:8000
[12/Mar/2021 09:52:31] "GET /api/v1/plays?order=-started&limit=50 HTTP/1.1" 200 409
http://127.0.0.1:8000 "GET /api/v1/plays?order=-started&limit=50 HTTP/1.1" 200 409
HTTP 200: get on /api/v1/plays
+----+-----------+----------------------+----------+-------+---------+----------------------------------+-----------------+
| id | status    | name                 | playbook | tasks | results | started                          | duration        |
+----+-----------+----------------------+----------+-------+---------+----------------------------------+-----------------+
|  1 | completed | hello world playbook |        1 |     2 |       2 | 2021-03-12T09:52:16.894087+01:00 | 00:00:02.910561 |
+----+-----------+----------------------+----------+-------+---------+----------------------------------+-----------------+
```
