### ISSUE TITLE
adding a possibilty to search for hosts on the starting page

### ISSUE THREAD

**Issue by hille721** [ansible-community/ara#218]
## What is the idea ?
It would be greate to have a possibilty to search for a host in the web ui of the api server:

![image](https://user-images.githubusercontent.com/38468371/110927585-1e94db80-8326-11eb-9fe1-564b1a189ea9.png)

The result shoud be then all playbook runs with this host.

**Comment by dmsimard** [comment]
Hi @hille721 and thanks for the issue.

I have a WIP PR for this though I do not have an ETA yet: https://github.com/ansible-community/ara/pull/206

In the meantime, this is already implemented in the CLI with the ``ara host list`` command: https://ara.readthedocs.io/en/latest/cli.html#ara-host-list

There is a ``name`` argument which lets you search for specific hosts.

**Comment by hille721** [comment]
Hi @dmsimard,

THAT IS AWESOME! :+1: 

just installed your PR branch and tested it, definitive more as I expected, but I love it! 
Is there anything where I can help you to finish it? Testing, checking your implementation, implement stuff, writinge documentation, ...?
Just let me know :-)

**Comment by hille721** [comment]
Hi @dmsimard,

THAT IS AWESOME! :+1: 

just installed your PR branch and tested it, definitive more as I expected, but I love it! 
Is there anything where I can help you to finish it? Testing, checking your implementation, implement stuff, writinge documentation, ...?
Just let me know :-)

**Comment by dmsimard** [comment]
Thanks for checking it out and appreciate the offer for help !

This is how I see things eventually playing out:
- The index of the built-in UI is the list of playbooks, analogous to ``ara playbook list`` on the CLI or [/api/v1/playbooks](https://demo.recordsansible.org/api/v1/playbooks) on the API
- The hosts page (i.e, the PR) would be analogous to ``ara host list`` and [/api/v1/hosts](https://demo.recordsansible.org/api/v1/hosts) for the API

Then, following the same pattern, we could have similar pages for plays, tasks and results.

For hosts specifically, I'm not sure I want to go there for a first implementation but I think there are opportunities for doing things like [ansible-cmdb](https://github.com/fboender/ansible-cmdb) since we also have host facts when they are gathered:
![screenshot-overview](https://user-images.githubusercontent.com/1291204/110987737-8acf0980-833d-11eb-843e-dddcb43fbae3.png)

For now the PR is almost ready to land and I can probably take care of it soon.
I would avoid starting work on plays, tasks and results until after I've finished doing a little facelift of the UI (WIP branch [here](https://github.com/dmsimard/ara/tree/wip-bootstrap) if you want to look) so we don't end up doing the work twice.

**Comment by hille721** [comment]
> The index of the built-in UI is the list of playbooks, analogous to ara playbook list on the CLI or /api/v1/playbooks on the API

I think that's fine, thus you have a direct overview which playbooks were running latest on your infrastructure


> The hosts page (i.e, the PR) would be analogous to ara host list and /api/v1/hosts for the API

As I already said, really like it. What's missing, and that I think are low hanging fruits, are more filters, e.g. for the status.


> For hosts specifically, I'm not sure I want to go there for a first implementation but I think there are opportunities for doing things like ansible-cmdb since we also have host facts when they are gathered

cool idea, but I think this just make sense when the hosts are unique. And currently there is just the uniqueness of the combination host and playbook run. It could be worth to change that, but I guess that 's a huge changesto the current model design. 

The facelift looking modern :+1: And I understood that it makes sense to do that first.

**Comment by dmsimard** [comment]
> > The hosts page (i.e, the PR) would be analogous to ara host list and /api/v1/hosts for the API
> 
> As I already said, really like it. What's missing, and that I think are low hanging fruits, are more filters, e.g. for the status.

The CLI has the following flags:
```
  --with-changed        Return hosts with changed results
  --without-changed     Don't return hosts with changed results
  --with-failed         Return hosts with failed results
  --without-failed      Don't return hosts with failed results
  --with-unreachable    Return hosts with unreachable results
  --without-unreachable Don't return hosts with unreachable results
```

From an API perspective, it looks like this: https://github.com/ansible-community/ara/blob/06851d8438ad43af7c1cceaecf5c407392966ee6/ara/cli/host.py#L130-L141

I plan on adding support for it to the PR before it's ready to land.

> > For hosts specifically, I'm not sure I want to go there for a first implementation but I think there are opportunities for doing things like ansible-cmdb since we also have host facts when they are gathered
> 
> cool idea, but I think this just make sense when the hosts are unique. And currently there is just the uniqueness of the combination host and playbook run. It could be worth to change that, but I guess that 's a huge changesto the current model design.

Right, the way I could have seen this working would be to pull only the latest record for every host instead of all of them.
This wouldn't require changing the model but there is no direct API call for providing this kind of view yet.

> The facelift looking modern +1 And I understood that it makes sense to do that first.

It's not finished but glad you like it \o/

**Comment by hille721** [comment]
> Right, the way I could have seen this working would be to pull only the latest record for every host instead of all of them.
This wouldn't require changing the model but there is no direct API call for providing this kind of view yet.

Honestly, that would be exactly what I'm looking for! A simple overview page where I can check the status of the last runs on a per host basis. You can then also add a summary on the top (100 ok, 20 changed, 5 failed, 2 unreachable), as you have it e.g. in AWX, Foreman, etc, :)

But I would separate this from the current planned host_index page, thus that you have both. A quick overview of the last runs per host, but also the possibility to check all last runs for ONE host.

**Comment by dmsimard** [comment]
> But I would separate this from the current planned host_index page, thus that you have both. A quick overview of the last runs per host, but also the possibility to check all last runs for ONE host.

Sure, those are not mutually exclusive :p

If you'd like to work on that, I haven't looked at how to do this in practice yet but there is some amount of literature on returning only the latest object with DRF: https://stackoverflow.com/questions/38869894/get-latest-object-with-filter-in-django-rest-framework

Our current view for hosts is this one: https://github.com/ansible-community/ara/blob/06851d8438ad43af7c1cceaecf5c407392966ee6/ara/api/views.py#L94-L105

So we'd need something similar with an extra filter on latest ? Once the endpoint is available, we can leverage it in the CLI and the UI.

**Comment by hille721** [comment]
I will look into that!

>If you'd like to work on that, I haven't looked at how to do this in practice yet but there is some amount of literature on returning only the latest object with DRF: https://stackoverflow.com/questions/38869894/get-latest-object-with-filter-in-django-rest-framework

I think our case is a bit more complex, because we do not want to have just the latest object, but want to get a set of the latest objects for each host.

Thus we need something as
`queryset = [ .objects.filter(id=obj.id).latest('created') for obj in .objects.all()]`
Will have a deeper look into it.

**Comment by dmsimard** [comment]
@hille721 I poked at this a bit yesterday while wondering whether this would land before the next release and you're right, it's not that simple. I like the idea but wonder what's the right approach and whether we might need to consider a change in the model to make it easier.

I can't seem to find a way to get the latest record for each host without first iterating over each host which could end up being expensive at scale. There is a noteworthy exception using ``distinct`` but it's postgresql-only.

How do you see this working in practice ? I thought perhaps we could have a ``latest`` argument on the ``/api/v1/hosts`` endpoint that would work a bit like this:
- ``/api/v1/hosts`` -> get all hosts (including "duplicates" across playbooks)
- ``/api/v1/hosts?latest=true`` -> get all hosts, filtering duplicates and only returning the latest entry for each host (expensive???)
- ``/api/v1/hosts?name=localhost`` -> get hosts matching localhost (including "duplicates" across playbooks)
- ``/api/v1/hosts?name=localhost&latest=true`` -> get hosts matching localhost but only return the latest (this should be fine and unexpensive)

**Comment by hille721** [comment]
@dmsimard : sorry, I was quite busy the last week, but a few days ago I already started to get familiar with the current API code and also already prepared my development environment :)

Furthermore I've also thought about a good entrypoint and I had exactly the same idea as you: an additional `latest` parameter for the `/api/v1/hosts` endpoint.
Yes, this `latest` could be a bool, but we could also make a more generic approach and use an integer instead with:

* `0`: get all hosts (equals to `false` in your idea)
* `1`: only returning the latest entry for each host (equals to `true` in your idea)
* `N > 1`:  only returning the last `N` entries for each host

To get a good performance this filtering should already happeining on database level, so we have to find a possibility within the QuerySet. Otherwise I also guess that it will be expensive and that wouldn't be much benefit for the user.
But I also don't know yet how we could realize it and what is the best approach.

**Comment by hille721** [comment]
@dmsimard: short update: I just implemented the idea above with iterating over each host, it works fine but as expected at scale it is very expensive.

[Here](https://github.com/hille721/ara/blob/2b0396e0dbd535c75e01b46d8510dcb540c27a61/ara/api/views.py#L114-L116) is what I've implemented.

First step is to iterating over all distinct hosts and getting the latest host id
``` python
latesthosts = [self.queryset.filter(name=host['name']).latest('created').id
                       for host in self.queryset.order_by('name').values('name').distinct()]
```
and then as second step, making a queryset again>
``` python
return self.queryset.filter(id__in=latesthosts)
```
For development purpose I've created a new endpoint /api/vi/latesthosts and the result with 22429 host objects (about 4030 distinct hosts) is as expected really bad:
* /api/v1/hosts: 0.6 seconds
* /api/v1/latesthosts: 157.9 seconds

That is even worse than I thought :-1:

**Comment by dmsimard** [comment]
@hille721 thanks for checking it out !

Some questions:
- Do you know which part takes the longest ?
- Would using ``group_by('name')`` to get the list of host names be faster/more efficient ?
- Your implementation doesn't seem to take into account a limit (or pagination) which means it has to iterate over the entire thing. Would that make it reasonably fast enough ?

**Comment by hille721** [comment]
> Do you know which part takes the longest ?

definitely step one, because we are doing ONE database call per EACH host. That's why I've already wrote above that we need to get that work inside a QuerySet, because they are lazy.

Without finding out all the latest ids, e.g. through replacing the first step with random ids:
``` python
import random
latesthosts = random.sample(range(0, 22428), 4030)
```
`/api/v1/latesthosts` is exactly that fast as `/api/v1/hosts`.

> Would using group_by('name') to get the list of host names be faster/more efficient ?

Seems to be that there is no such method on a QuerySet?

> Your implementation doesn't seem to take into account a limit (or pagination) which means it has to iterate over the entire thing. Would that make it reasonably fast enough ?

the pagination should be exactly the same as for the `hosts` endpoint because I've only change the `get_queryset()` method?
Or am I wrong.

What is really missing in my implementation: if you would filter for e.h. a host, this is not applied in the `get_queryset()` and would also take that long as you would go for all hosts. But my implementation was just a fast thing to check how long such a approach would take. And of course in the end, we would have to put it somewhere else.

**Comment by kfiresmith** [comment]
Very very much looking forward to feature.  Hopefully a progressive load for hosts can make this manageable.   In my environment I only have 300 hosts to worry about.   Perhaps until optimized it could be  an optional feature toggled within the app?

**Comment by hille721** [comment]
> Very very much looking forward to feature. Hopefully a progressive load for hosts can make this manageable. In my environment I only have 300 hosts to worry about. Perhaps until optimized it could be an optional feature toggled within the app?

Hi @kfiresmith, sure with less hosts my code above would be faster, but the runtime scales really bad, for each host more, one database query more is needed, thus you have `N+1` DB calls for `N` hosts.

But I want to highlight that the difficulty is only if we want a page with a distinct list of hosts. And I personally do not really need that. Sure such an Ansible CMDB would be nice, but in my opinion we have here the wrong model for that.
But easy will be a page with all hosts (a so called host index page) as @dmsimard already worked on in #206 and I guess a seach for a host name directly on the playbook root index should be also possible. Just to remember, that was the topic of this issue :)

**Comment by hille721** [comment]
Update: I've just pushed a WIP PR (#247) with another approach for further discussions.

**Comment by hille721** [comment]
closed this issue. Further discussions below the PR #247
