### ISSUE TITLE
api server ui: broken link in playbook.html

### ISSUE THREAD

**Issue by hille721** [ansible-community/ara#219]
## What is the issue ?

The link to [ara_records](https://ara.readthedocs.io/en/latest/ara-record.html) in the `playbook.html` template does not work anymore:
https://github.com/ansible-community/ara/blame/master/ara/ui/templates/playbook.html#L17

## What should be happening ?
I'm not sure about the correct link, but maybe this one: https://ara.readthedocs.io/en/latest/ansible-plugins-and-use-cases.html?#ara-record-arbitrary-key-values-in-playbook-reports

**Comment by dmsimard** [comment]
Good catch!

I can see the destination of that link changing eventually and keeping the links working through documentation refactors is not always easy. I'll think of something or update it to a more generic link that isn't as likely to change.

**Comment by dmsimard** [comment]
This will be fixed (amongst other things) by the UI refactor in https://github.com/ansible-community/ara/pull/225

**Comment by dmsimard** [comment]
Going to close this since it's merged. Will be in the next release: 1.5.6.
