### ISSUE TITLE
Ara is logging to stdout together with Ansible resulting in weird output

### ISSUE THREAD

**Issue by eRadical** [ansible-community/ara#228]
## What is the issue ?
Ara is logging to stdout together w/ Ansible resulting in garbled output hard to read.
If I'm unsetting ara's callbacks Ansible's output is back.

```
$ ansible-playbook ara-breaks-stdout-logging.yaml 
Operations to perform:
  Apply all migrations: admin, api, auth, contenttypes, db, sessions
Running migrations:
  No migrations to apply.

PLAY [Example] *************************************************************************************************************************
2021-03-23 13:54:09,721 INFO ansible: PLAY [Example] *************************************************************************************************************************

TASK [a shell command] *****************************************************************************************************************
2021-03-23 13:54:09,815 INFO ansible: TASK [a shell command] *****************************************************************************************************************
Tuesday 23 March 2021  13:54:09 +0200 (0:00:00.791)       0:00:00.791 ********* 
2021-03-23 13:54:09,831 INFO ansible: Tuesday 23 March 2021  13:54:09 +0200 (0:00:00.791)       0:00:00.791 ********* 
changed: [localhost]
2021-03-23 13:54:10,108 INFO ansible: changed: [localhost]

PLAY RECAP *****************************************************************************************************************************
2021-03-23 13:54:10,151 INFO ansible: PLAY RECAP *****************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2021-03-23 13:54:10,151 INFO ansible: localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
2021-03-23 13:54:10,298 INFO ansible: Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
Tuesday 23 March 2021  13:54:10 +0200 (0:00:00.466)       0:00:01.258 ********* 
2021-03-23 13:54:10,298 INFO ansible: Tuesday 23 March 2021  13:54:10 +0200 (0:00:00.466)       0:00:01.258 ********* 
=============================================================================== 
2021-03-23 13:54:10,298 INFO ansible: =============================================================================== 
a shell command ----------------------------------------------------------------------------------------------------------------- 0.47s
2021-03-23 13:54:10,298 INFO ansible: a shell command ----------------------------------------------------------------------------------------------------------------- 0.47s
```

The beginning part `Operations to perform` and `Running migrations` is coming from Ara.
The same for lines containing `INFO ansible:`.

After unsetting callbacks all is back to normal:
```
$ unset ANSIBLE_LOOKUP_PLUGINS ANSIBLE_CALLBACK_PLUGINS ANSIBLE_ACTION_PLUGINS
$ ansible-playbook ara-breaks-stdout-logging.yaml 

PLAY [Example] *************************************************************************************************************************

TASK [a shell command] *****************************************************************************************************************
Tuesday 23 March 2021  14:00:30 +0200 (0:00:00.010)       0:00:00.010 ********* 
changed: [localhost]

PLAY RECAP *****************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
Tuesday 23 March 2021  14:00:30 +0200 (0:00:00.249)       0:00:00.260 ********* 
=============================================================================== 
a shell command ----------------------------------------------------------------------------------------------------------------- 0.25s
```
But I'm loosing Ara functionality for that run.

I'm on Fedora 33 but installed ansible & ara via pip.
```
$ pip3 list | grep -P "^ansible|^ara"
ansible                               3.0.0
ansible-base                          2.10.7
ansible-lint                          5.0.3
ara                                   1.5.4
```

## What should be happening ?
Ara should not influence stdout of an ansible run, except when explicitly configured by the user.

**Comment by eRadical** [comment]
Further investigations shows the following.

If I have in `ansible.cfg`:
```
log_path = ~/.ansible/ansible.log
```
I'll get the garbled output because of the part `INFO ansible:`.
Else the output is ok.

However I always get the part:
```
Operations to perform:
  Apply all migrations: admin, api, auth, contenttypes, db, sessions
Running migrations:
  No migrations to apply.
```

**Comment by dmsimard** [comment]
Hi @eRadical and thanks for the issue.

I suspect that the python logging configuration between ara and ansible are getting mixed up.

In ``~/.ara/server/settings.yaml`` you should have a python logging configuration that looks more or less like this:
```yaml
LOGGING:
  disable_existing_loggers: false
  formatters:
    normal:
      format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: normal
      level: INFO
      stream: ext://sys.stdout
  loggers:
    ara:
      handlers:
      - console
      level: INFO
      propagate: 0
  root:
    handlers:
    - console
    level: INFO
  version: 1
```

The logging that Ansible sets up here located around these parts:
https://github.com/ansible/ansible/blob/a520da05842cdd3db820963470c436c1078ac54f/lib/ansible/utils/display.py#L172-L184

I would expect that the ``propagate: 0`` from the ara configuration avoid this conflict from happening but apparently that's not the case and we would need to investigate why because I don't have an answer right now.

**Comment by eRadical** [comment]
Yes... all that is in place.

I'm here if you need to test anything.

Thank you for your help!

**Comment by dmsimard** [comment]
@eRadical I don't expect to have time to troubleshoot this issue before the upcoming release (1.5.6) and I don't see it as a blocker for now.

If you or someone else can investigate the relationship and conflict between the ara and ansible logging that'd be great but otherwise it will need to wait until I can circle back to it.

**Comment by jwkenney** [comment]
Just encountered this issue with a plain /out-of-box installation of ARA using pip.

A simple workaround for users to employ to cut down on the output, is to set LOG_LEVEL to WARN in settings.yaml. At least it avoids the double output on every task.

**Comment by nathanfms** [comment]
I ran into this and fixed it by modifying `server/settings.py` which to me looked like it wasn't actually loading the configuration from the `settings.yaml` file. It loaded the overall `LOG_LEVEL` from this file, but the custom log configuration options pulled from `settings.yaml` didn't actually do anything, all loggers listed got set to whatever was in `LOG_LEVEL`.

I fixed it by modifying `server/settings.py` to set `LOGGING = settings.get("LOGGING", <default logging options>)` and then modifying my `settings.yaml` `LOGGING.handlers.console.level` to be "ERROR"

**Comment by DataHearth** [comment]
Hey! I'm also facing this issue. 

I'm currently working on it by debugging everything related to ARA. I'll let you know here when something is found and/or fixed :smile: . 

@nathanfms you're right. The default logging configuration doesn't gather the user configuration before setting the default one. I have already fix it with my local branch. It'll submit it when the logging error is also fixed ^^.

**Comment by dmsimard** [comment]
Should have been fixed by https://github.com/ansible-community/ara/pull/367 released in 1.5.8

**Comment by DataHearth** [comment]
@eRadical This not from ARA properly speaking, it's from the Django framework. If you wish to mute that warning, you should look at the framework documentation :)

**Comment by eRadical** [comment]
Thank you @DataHearth  - It's not that disturbing as it is once per playbook.

Ansible output is now clean and readable!
