### ISSUE TITLE
Users should be able to see ARA application info in UI

### ISSUE THREAD

**Issue by kfiresmith** [ansible-community/ara#248]
## What is the idea ?
In the ARA UI, it would be nice if you could view typical "About" information (ARA version, etc) via the normal convention of clicking an about icon in the upper right quadrant of the web UI.  See Gitlab screenshot as an example.

Additionally, not sure if this can work with htpasswd-based auth as is used in ARA web UI, but being able see who you are logged in as, and to "logout" (flushing what I assume is a cookie or something) via the user UI as well.  

![image](https://user-images.githubusercontent.com/8343629/113599291-64cf1900-960c-11eb-8fe7-fa406a300e22.png)

**Comment by dmsimard** [comment]
I'll close this issue since it landed in 1.5.6 via https://github.com/ansible-community/ara/pull/257
