### ISSUE TITLE
Install from local archives failed

### ISSUE THREAD

**Issue by Taurus-Le** [ansible-community/ara#270]
## What is the issue ?
Dear all, I tried to install ARA from local archives for the reason of  network isolation.
First, I installed ARA from PyPi and recorded every dependency showing in the stdout.
And then I downloaded them manually from 'pypi.org' and placed them under '/root/ARA/'

After all packages prepared, I tried installing ARA using the tarball.
Below is the command that I used:
`pip3.7 install ara-1.5.6.tar.gz --no-index --find-links=file:///root/ARA`

Here is the error message I got:
> Looking in links: file:///root/ARA
Processing ./ara-1.5.6.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-tr4ocj_0/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-tr4ocj_0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-tr4ocj_0/
    Complete output (16 lines):
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-req-build-tr4ocj_0/.eggs/pbr-5.6.0-py3.7.egg/pbr/core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-req-build-tr4ocj_0/.eggs/pbr-5.6.0-py3.7.egg/pbr/util.py", line 274, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "/tmp/pip-req-build-tr4ocj_0/.eggs/pbr-5.6.0-py3.7.egg/pbr/hooks/__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "/tmp/pip-req-build-tr4ocj_0/.eggs/pbr-5.6.0-py3.7.egg/pbr/hooks/base.py", line 27, in run
        self.hook()
      File "/tmp/pip-req-build-tr4ocj_0/.eggs/pbr-5.6.0-py3.7.egg/pbr/hooks/metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "/tmp/pip-req-build-tr4ocj_0/.eggs/pbr-5.6.0-py3.7.egg/pbr/packaging.py", line 880, in get_version
        name=package_name))
    Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name ara was given, but was not able to be found.
    error in setup command: Error parsing /tmp/pip-req-build-tr4ocj_0/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name ara was given, but was not able to be found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I found an question on stackoverflow:
[https://stackoverflow.com/questions/58854822/python-setup-py-sdist-error-versioning-for-this-project-requires-either-an-sdist](url)

I followed the instruction setting PBR_VERSION by executing command below:
`export PBR_VERSION=1.5.6`
This time everything seemed OK. 
I ran the command below to get rid of the migration warnings:
`ara-manage migrate`
Things stiil seemed OK,

> [ara] No setting found for SECRET_KEY. Generating a random key...
[ara] Creating data & configuration directory: /root/.ara/server
[ara] Writing default settings to /root/.ara/server/settings.yaml
[ara] Using settings file: /root/.ara/server/settings.yaml
Operations to perform:
  Apply all migrations: admin, api, auth, contenttypes, db, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying api.0001_initial... OK
  Applying api.0002_remove_host_alias... OK
  Applying api.0003_add_missing_result_properties... OK
  Applying api.0004_duration_in_database... OK
  Applying api.0005_unique_label_names... OK
  Applying api.0006_remove_result_statuses... OK
  Applying api.0007_add_expired_status... OK
  Applying api.0008_playbook_controller... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK

But when I tried to visit the ARA web. Things went wrong:

> [ara] Using settings file: /root/.ara/server/settings.yaml
[ara] Using settings file: /root/.ara/server/settings.yaml
2021-04-27 17:00:27,505 INFO django.utils.autoreload: Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 27, 2021 - 17:00:27
Django version 3.2, using settings 'ara.server.settings'
Starting development server at http://192.168.25.128:8000/
Quit the server with CONTROL-C.
2021-04-27 17:00:36,866 ERROR django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.7/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/renderers.py", line 160, in render
    template = self.resolve_template(template_names)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html

I checked the path:

> /usr/local/lib/python3.7/site-packages/ara/ui

It seems that directory `templates` is missing.

I am quite confused that what went wrong? Am I missing any prerequisite? What's the difference between installing from internet and from local archive?

## Environment
OS:                    Red Hat Enterprise Linux Server 7.5 (Maipo)
Kernel:               Linux 3.10.0-862.el7.x86_64
Python:              Python 3.7.6

**Comment by Taurus-Le** [comment]
Dear all,
I just found that web server seemed OK after copying the directories below into `/usr/local/lib/python3.7/site-packages/ara/ui`.

> management
static
templates
templatetags

Any information about why these directories weren't copied into `/usr/local/lib/python3.7/site-packages/ara/ui`?

**Comment by kfiresmith** [comment]
So this isn't the answer you are looking for @Taurus-Le, but I did want to chime in that this seems like a good opportunity to use the ARA container instead, as you could do a `docker image save`, `docker image load`, to carry ARA across the air-gap in a clean way.

**Comment by dmsimard** [comment]
Hi @Taurus-Le and thanks for the issue.

> Any information about why these directories weren't copied into /usr/local/lib/python3.7/site-packages/ara/ui

It doesn't ring me a bell at first glance. Do you think it would be possible to provide the commands to reproduce the steps to reproduce the issue ?

I've tried installing from the tarball and the files are there:
```bash
> wget https://files.pythonhosted.org/packages/21/8b/e02fd403ce20699e638d428f4108caa466633b6da3ccf4b8207055f10b32/ara-1.5.6.tar.gz
--2021-04-27 10:51:50--  https://files.pythonhosted.org/packages/21/8b/e02fd403ce20699e638d428f4108caa466633b6da3ccf4b8207055f10b32/ara-1.5.6.tar.gz
Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.1.63, 151.101.65.63, 151.101.129.63, ...
Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.1.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5657676 (5.4M) [application/x-tar]
Saving to: ‘ara-1.5.6.tar.gz’

ara-1.5.6.tar.gz                                                       100%[============================================================================================================================================================================>]   5.40M  19.2MB/s    in 0.3s    

2021-04-27 10:51:51 (19.2 MB/s) - ‘ara-1.5.6.tar.gz’ saved [5657676/5657676]

> python3 -m venv /tmp/test-tarball
> /tmp/test-tarball/bin/pip install ara-1.5.6.tar.gz
Processing ./ara-1.5.6.tar.gz
Collecting pbr!=2.1.0,>=2.0.0
  Using cached pbr-5.6.0-py2.py3-none-any.whl (111 kB)
Collecting cliff
  Using cached cliff-3.7.0-py3-none-any.whl (80 kB)
Collecting requests>=2.14.2
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting PyYAML>=3.12
  Using cached PyYAML-5.4.1-cp39-cp39-manylinux1_x86_64.whl (630 kB)
Collecting PrettyTable>=0.7.2
  Using cached prettytable-2.1.0-py3-none-any.whl (22 kB)
Collecting cmd2>=1.0.0
  Using cached cmd2-1.5.0-py3-none-any.whl (133 kB)
Collecting pyparsing>=2.1.0
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting stevedore>=2.0.1
  Using cached stevedore-3.3.0-py3-none-any.whl (49 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting colorama>=0.3.7
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting attrs>=16.3.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Processing /home/dmsimard/.cache/pip/wheels/0c/09/9e/49e21a6840ef7955b06d47394afef0058f0378c0914e48b8b8/pyperclip-1.8.2-py3-none-any.whl
Using legacy 'setup.py install' for ara, since package 'wheel' is not installed.
Installing collected packages: pbr, PyYAML, wcwidth, PrettyTable, colorama, attrs, pyperclip, cmd2, pyparsing, stevedore, cliff, urllib3, certifi, chardet, idna, requests, ara
    Running setup.py install for ara ... done
Successfully installed PrettyTable-2.1.0 PyYAML-5.4.1 ara-1.5.6 attrs-20.3.0 certifi-2020.12.5 chardet-4.0.0 cliff-3.7.0 cmd2-1.5.0 colorama-0.4.4 idna-2.10 pbr-5.6.0 pyparsing-2.4.7 pyperclip-1.8.2 requests-2.25.1 stevedore-3.3.0 urllib3-1.26.4 wcwidth-0.2.5
WARNING: You are using pip version 20.2.2; however, version 21.1 is available.
You should consider upgrading via the '/tmp/test-tarball/bin/python3 -m pip install --upgrade pip' command.

> tree -L 2 /tmp/test-tarball/lib/python3.9/site-packages/ara
/tmp/test-tarball/lib/python3.9/site-packages/ara
├── api
│   ├── admin.py
│   ├── apps.py
│   ├── auth.py
│   ├── fields.py
│   ├── filters.py
│   ├── __init__.py
│   ├── management
│   ├── migrations
│   ├── models.py
│   ├── __pycache__
│   ├── serializers.py
│   ├── tests
│   ├── urls.py
│   └── views.py
├── cli
│   ├── base.py
│   ├── expire.py
│   ├── host.py
│   ├── __init__.py
│   ├── playbook.py
│   ├── play.py
│   ├── prometheus.py
│   ├── __pycache__
│   ├── record.py
│   ├── result.py
│   ├── task.py
│   └── utils.py
├── clients
│   ├── http.py
│   ├── __init__.py
│   ├── offline.py
│   ├── __pycache__
│   └── utils.py
├── plugins
│   ├── action
│   ├── callback
│   └── lookup
├── server
│   ├── admin.py
│   ├── apps.py
│   ├── context_processors.py
│   ├── db
│   ├── __init__.py
│   ├── __main__.py
│   ├── __pycache__
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
├── setup
│   ├── action_plugins.py
│   ├── ansible.py
│   ├── callback_plugins.py
│   ├── env.py
│   ├── exceptions.py
│   ├── __init__.py
│   ├── lookup_plugins.py
│   ├── path.py
│   ├── plugins.py
│   ├── __pycache__
│   └── README.rst
└── ui
    ├── apps.py
    ├── forms.py
    ├── __init__.py
    ├── management
    ├── pagination.py
    ├── __pycache__
    ├── static
    ├── templates
    ├── templatetags
    ├── urls.py
    └── views.py

24 directories, 49 files
```

**Comment by Taurus-Le** [comment]
> So this isn't the answer you are looking for @Taurus-Le, but I did want to chime in that this seems like a good opportunity to use the ARA container instead, as you could do a `docker image save`, `docker image load`, to carry ARA across the air-gap in a clean way.

Thanks for the replay.  The reason I'm not using docker is that I've never used it before. It might take some time for me to get familiar with it. I will learn it after this, because container will save me a lot trouble as you mentioned.

**Comment by Taurus-Le** [comment]
Hi @dmsimard and thanks for replying.
I noticed you installed ARA in the virtual environment, which I did not. Below is the steps I took:

1. Download and install sqlite from official website: [https://www.sqlite.org/2021/sqlite-autoconf-3350500.tar.gz](url)

```shell
tar -zxvf sqlite-autoconf-3350500.tar.gz
cd sqlite-autoconf-3350500
./configure
make && make install
cd ..
```

2. Download and install Python 3.7.6

```shell
tar -xvf Python-3.7.6.tgz
cd Python-3.7.6
LD_RUN_PATH=/usr/local/lib ./configure
LD_RUN_PATH=/usr/local/lib make && make altinstall
cd ..
```

3. Download requests and all its dependencies into `/root/Requests`

> certifi-2020.12.5-py2.py3-none-any.whl
chardet-4.0.0-py2.py3-none-any.whl
idna-2.10-py2.py3-none-any.whl
requests-2.25.1-py2.py3-none-any.whl
urllib3-1.26.4-py2.py3-none-any.whl

```shell
# install requests
cd Requests/
pip3.7 install requests-2.25.1-py2.py3-none-any.whl --no-index --find-links=file://${PWD}
cd ..
```
4. Download Django and all its dependencies into `/root/Django/`

> asgiref-3.3.4-py3-none-any.whl
Django-3.2-py3-none-any.whl
pytz-2021.1-py2.py3-none-any.whl
sqlparse-0.4.1-py3-none-any.whl
typing_extensions-3.7.4.3-py3-none-any.whl

```shell
# install Django
cd Django/
pip3.7 install Django-3.2-py3-none-any.whl --no-index --find-links=file://${PWD}
cd ..
```
5. Download ARA and all its dependencies into `/root/ARA/`

> ara-1.5.6.tar.gz
attrs-20.3.0-py2.py3-none-any.whl
cliff-3.7.0-py3-none-any.whl
clinner-1.12.3-py3-none-any.whl
cmd2-1.5.0-py3-none-any.whl
colorama-0.4.4-py2.py3-none-any.whl
colorlog-3.2.0-py2.py3-none-any.whl
django_cors_headers-3.7.0-py3-none-any.whl
django_filter-2.4.0-py3-none-any.whl
django_health_check-3.16.4-py2.py3-none-any.whl
djangorestframework-3.12.4-py3-none-any.whl
dynaconf-3.1.4-py2.py3-none-any.whl
gitdb-4.0.7-py3-none-any.whl
GitPython-3.1.14-py3-none-any.whl
health_check-3.4.1-py2.py3-none-any.whl
importlib_metadata-4.0.1-py3-none-any.whl
pbr-5.6.0-py2.py3-none-any.whl
prettytable-2.1.0-py3-none-any.whl
Pygments-2.8.1-py3-none-any.whl
pyparsing-2.4.7-py2.py3-none-any.whl
pyperclip-1.8.2.tar.gz
PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl
smmap-4.0.0-py2.py3-none-any.whl
stevedore-3.3.0-py3-none-any.whl
tzlocal-2.1-py2.py3-none-any.whl
wcwidth-0.2.5-py2.py3-none-any.whl
whitenoise-5.2.0-py2.py3-none-any.whl
zipp-3.4.1-py3-none-any.whl
```shell
# install ARA
cd ARA/
export PBR_VERSION=1.5.6
pip3.7 install ara-1.5.6.tar.gz --no-index --find-links=file://${PWD}
pip3.7 install tzlocal-2.1-py2.py3-none-any.whl
pip3.7 install dynaconf-3.1.4-py2.py3-none-any.whl
pip3.7 install health_check-3.4.1-py2.py3-none-any.whl --no-index --find-links=file://${PWD}
pip3.7 install django_health_check-3.16.4-py2.py3-none-any.whl
pip3.7 install django_cors_headers-3.7.0-py3-none-any.whl
pip3.7 install djangorestframework-3.12.4-py3-none-any.whl
pip3.7 install django_filter-2.4.0-py3-none-any.whl
pip3.7 install whitenoise-5.2.0-py2.py3-none-any.whl
pip3.7 install Pygments-2.8.1-py3-none-any.whl
cd ..
```
And if remove the command ``, I would get the error messages:
   Looking in links: file:///root/ARA
Processing ./ara-1.5.6.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-tfosgj8f/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-tfosgj8f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-tfosgj8f/
    Complete output (16 lines):
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-req-build-tfosgj8f/.eggs/pbr-5.6.0-py3.7.egg/pbr/core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-req-build-tfosgj8f/.eggs/pbr-5.6.0-py3.7.egg/pbr/util.py", line 274, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "/tmp/pip-req-build-tfosgj8f/.eggs/pbr-5.6.0-py3.7.egg/pbr/hooks/__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "/tmp/pip-req-build-tfosgj8f/.eggs/pbr-5.6.0-py3.7.egg/pbr/hooks/base.py", line 27, in run
        self.hook()
      File "/tmp/pip-req-build-tfosgj8f/.eggs/pbr-5.6.0-py3.7.egg/pbr/hooks/metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "/tmp/pip-req-build-tfosgj8f/.eggs/pbr-5.6.0-py3.7.egg/pbr/packaging.py", line 880, in get_version
        name=package_name))
    Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name ara was given, but was not able to be found.
    error in setup command: Error parsing /tmp/pip-req-build-tfosgj8f/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name ara was given, but was not able to be found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Taurus-Le** [comment]
Dear @dmsimard,
I found that even I seemed to install ARA successfully with the steps I provided. ARA is not working properly. I created a simple test playbook and ran it with Ansible 2.10.8. The ARA web showed nothing at all. I found several more directories are missing.

    ara/api/management
    ara/plugins
    ara/server/db
    ara/ui/management
    ara/ui/static
    ara/ui/templatetags

I copied the directories above except `ara/server/db` into `/usr/local/lib/python3.7/site-packages/ara` manually. And everything seemed working properly.

Oh, sorry for the missing Ansible information.

    ansible 2.10.8
      config file = /etc/ansible/ansible.cfg
      configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
      executable location = /usr/local/bin/ansible
      python version = 3.7.6 (default, Apr 27 2021, 14:59:30) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

**Comment by Taurus-Le** [comment]
Dear @dmsimard,
I think I found the reason.
The tarball which I used is downloaded from
[https://github.com/ansible-community/ara/releases](url)
I ran md5sum against it, below is the result:

    05f31e72ae0771c81c809f77843ca099
The tarball which you used is downloaded from
[https://files.pythonhosted.org/packages/21/8b/e02fd403ce20699e638d428f4108caa466633b6da3ccf4b8207055f10b32/ara-1.5.6.tar.gz](url)
I also ran md5sum against it, below is the result:

    0cf38411bbb432a85d0a156bb8a09628

I used your tarball and problem solved. I just need to ran the command below. Setting `PBR_VERSION` is no longer needed.
`pip3.7 install ara-1.5.6.tar.gz --no-index --find-links=file://${PWD}`

So these two tarballs are different. Any idea what's the difference?

**Comment by hille721** [comment]
Hi,
this error 

> ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-tr4ocj_0/setup.py'"'"'; file='"'"'/tmp/pip-req-build-tr4ocj_0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info

is exactly the problem if I am trying to install ara 1.5.5 or 1.5.6 from our company artifactory (see this issue #236). 

My workaround is still to install 1.5.4 and then do a upgrade to the newest version :/

**Comment by hille721** [comment]
Just solved my problem by upgrading setuptools :)

@Taurus-Le : have you checked your setuptools version? Maybe your problem has nothing to do with the different tarballs but rather with the setuptools version.

**Comment by dmsimard** [comment]
> So these two tarballs are different. Any idea what's the difference?

@Taurus-Le releases are published to PyPi independently of GitHub -- there is a git tag of the repository for the release and then GitHub provides an archive for that but it's not this archive that ends up being published to PyPi.

What you are getting through the GitHub tarball is an archive of the git repository, not the actual python sdist package that gets uploaded to PyPi so that could explain the differences between the two.

**Comment by dmsimard** [comment]
> Just solved my problem by upgrading setuptools

@hille721 this is interesting. I wonder if we should declare an explicit version requirement range for setuptools in our requirements.txt ?

**Comment by Taurus-Le** [comment]
@hille721 
Thanks for the tips  :)
Mine mistake is that I used the wrong tarball with the same name which exactly is my bad.

**Comment by Taurus-Le** [comment]
@dmsimard 
Thanks for the clarification :)
I will close this issue as the "problem" has been solved.
