### ISSUE TITLE
Can send mail summary report？

### ISSUE THREAD

**Issue by zyayun** [ansible-community/ara#278]
Can I send a summary email report?

**Comment by dmsimard** [comment]
@zyayun what kind of email do you have in mind ? 

ARA doesn't send emails but there is nothing preventing you from sending emails with data from ara and maybe even links to the playbook reports.

I don't have an example like that on hand but here's a slack notification playbook that you might be able to draw inspiration from: https://github.com/ansible-community/ara/blob/master/contrib/playbooks/slack-notifications.yaml

**Comment by flowerysong** [comment]
I use a second callback to send playbook failure reports (in my case via AWS SNS, but you could use the same approach for any notification method.) https://gitlab.umich.edu/ITS/inf/core-infrastructure-and-automation/mail-routing/ansible-aws/-/blob/main/ansible/callback_plugins/sns.py

**Comment by dmsimard** [comment]
@flowerysong very nice approach, I like it !

It's cool that you managed to find out how to retrieve the active client and figure out the playbook ID like the ara_record module does: https://gitlab.umich.edu/ITS/inf/core-infrastructure-and-automation/mail-routing/ansible-aws/-/blob/main/ansible/callback_plugins/sns.py#L143-149 :+1:

**Comment by zyayun** [comment]
@dmsimard  @flowerysong @dmsimard  Thanks a lot for your advice
