### ISSUE TITLE
Make playbook.arguments available in playbook list

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#28]
playbook.arguments is more or less a fixed size dict and we can afford to make it available in the playbook list call.

This will be useful for things like highlighting playbooks that ran with ``--check`` without needing to do a call for the playbook details. Example: https://github.com/ansible-community/ara-web/issues/6

**Comment by dmsimard** [comment]
Merged as https://review.opendev.org/#/c/657847/

**Comment by rntbrgtt** [comment]
Hi,

I am sorry but I am using ARA 1.4 and running DryRuns here (--check) and I cant see it anywhere.

Am I missing something?

Regards,

**Comment by dmsimard** [comment]
Hi @rntbrgtt, this issue was about the API implementation so if you request ``/api/v1/playbooks`` the arguments are available.

These are not exposed in the reporting UI yet but is planned for the 1.5 release which will include UI refactoring work. You can see what the progress looks like so far on https://api.trunk.demo.recordsansible.org.

**Comment by rntbrgtt** [comment]
Thanks for your quick reply.
New version looks awesome but I still can't see 'check = true' on the demo.
Will we be able to filter by remote_user as well?

**Comment by dmsimard** [comment]
"check" as well as "remote_user" are available in the CLI arguments:
![Screenshot from 2020-06-01 10-05-28](https://user-images.githubusercontent.com/1291204/83417070-945f3480-a3ef-11ea-9c85-b32729386272.png)

It is not possible to filter by CLI arguments yet but it was requested in another issue: https://github.com/ansible-community/ara/issues/119

In the meantime, I would like the --check playbooks to be highlighted differently in the playbook list and this can be done fairly easily without needing to implement the filtering.

**Comment by rntbrgtt** [comment]
I personally think that remote_user is as important as check to be shown on playbooks list but anyway I really appreciate your time to reply my messages and your help with the community.

**Comment by dmsimard** [comment]
@rntbrgtt happy to help :tada:

ARA has a LOT of data to work with and it's definitely challenging from a UI/UX perspective to display everything in a way that makes sense.

For now my main objective is to at least expose the data and demonstrate the features working -- then, hopefully someone with expertise in frontend can come in and make it pretty and usable :)

**Comment by dmsimard** [comment]
Hey @rntbrgtt o/

I am experimenting with an implementation that might work for the needs of highlighting ``remote_user`` and ``--check`` and making them searchable and wanted to know what you thought about it:

![Screenshot from 2020-09-18 10-54-05](https://user-images.githubusercontent.com/1291204/93635548-7af2f000-f9c0-11ea-9935-0a62fc55ac1d.png)

The way it would work with [this patch](https://review.opendev.org/#/c/752259/2/ara/plugins/callback/ara_default.py) is that the callback could be configured to automatically label playbooks after certain CLI arguments (such as ``--check`` and ``--user``).

Once labelled, it also enables search for those labels and this becomes sort of a workaround for lack of search for CLI arguments.

Let me know what you think :)

**Comment by rntbrgtt** [comment]
Hi @dmsimard ,

Thanks a lot for your effort on this project.

Showing remote_user and if it's a dry run or not and then being able to use this on to filter the search would be perfect for me. This looks awesome.

Looking forward to upgrading my ARA.

Regards,

**Comment by dmsimard** [comment]
@rntbrgtt thanks for the quick feedback, much appreciated !

This is the last change to land before the release of v1.5 so unless anything goes wrong it should be out next week.
