### ISSUE TITLE
Add support for recording diffs

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#29]
Diffs are available from the callback but they are currently discarded:

https://github.com/ansible/ansible/blob/7b7d6a1fef42eed7e144a7c391817a0a8263c3ae/lib/ansible/plugins/callback/__init__.py#L113-L115

We can retrieve the diff before it is discarded around here:
https://github.com/ansible-community/ara/blob/d56c68f749476e761d7d62a60c6d8843b95bf5eb/ara/plugins/callback/ara_default.py#L289

The diff printed by Ansible looks like this:
```
TASK [template] **********************************************************************************************************************
--- before: /tmp/foo
+++ after: /home/fedora/.ansible/tmp/ansible-local-25447850rn27v/tmpu1ngsu7a/foo.j2
@@ -1 +1 @@
-this is a roary
+this is a roar
```

And this is the format in which the data is available from the callback:
```
[{'before_header': '/tmp/foo', 'before': 'this is a roary\n', 'after_header': '/home/fedora/.ansible/tmp/ansible-local-25447850rn27v/tmpu1ngsu7a/foo.j2', 'after': 'this is a roar\n'}]
```

It seems like this would be an addition to the result model. A diff column which would default to null. From a web client perspective, the diff could be displayed if there is one.

**Comment by FlorianLaunay** [comment]
Any news on this maybe awesome feature ?

**Comment by dmsimard** [comment]
Pinging interested parties FYI: @FlorianLaunay @binrick, @yannfill, @hairmare, @mmcnl, @anayrat

Revisiting this and it looks like the diff is now saved in the result's content out of the box when running a playbook with ``--diff`` (probably since https://github.com/ansible-community/ara/commit/dce9f3a5171991f849b9817faca11d17983e8229 which landed in 1.4.0, thanks @flowerysong!):
![Screenshot from 2020-05-12 16-56-38](https://user-images.githubusercontent.com/1291204/81744740-96c61280-9471-11ea-92d1-42a8bcdd3e00.png)

So I guess it would be a matter of just rendering it nicely in the UI (i.e, with red/green) similar to what Ansible does because right now it's just pretty printed:
![Screenshot from 2020-05-12 16-57-39](https://user-images.githubusercontent.com/1291204/81744832-bb21ef00-9471-11ea-9344-22d429eb9db2.png)

For reference, the output from the Ansible playbook looks like this:
![Screenshot from 2020-05-12 16-59-40](https://user-images.githubusercontent.com/1291204/81745046-1358f100-9472-11ea-81c0-57fa9d8b9ea7.png)

The place where we would format this would be here:
https://github.com/ansible-community/ara/blob/2e367aff9e1d8b44e1cace56d50a578324d89d3d/ara/ui/templates/result.html#L31-L36

I can find time to do this but it's also something that would hopefully be simple enough to pick up if someone would like to contribute it. Please let me know if you'd like to work on this !

**Comment by dmsimard** [comment]
I'll pick this up for 1.5 UI work.

**Comment by dmsimard** [comment]
Work in progress: https://review.opendev.org/#/c/733422/

**Comment by bendem** [comment]
Is there a possibility to land support for string diffs while tackling complex types later?

**Comment by dmsimard** [comment]
Sorry, I wanted to release this in 1.5 but it'll be delayed (there's so much new stuff).

I'm still interested in landing this but it can go into a dot release easily.

**Comment by vincentbernat** [comment]
Hey @dmsimard! Any chance you can merge this for the next release?

Thanks.

**Comment by dmsimard** [comment]
@vincentbernat thanks for the reminder -- I think we can do it :+1: 

I'll rebase https://review.opendev.org/c/recordsansible/ara/+/733422 and try to figure out the right implementation for it.

**Comment by dmsimard** [comment]
o/ just reporting on progress -- I've been iterating on it for a bit and there are still issues that need to be worked out.

I've tested by searching for modules which have a diff implementation with roughly the same convention: https://codesearch.recordsansible.org/?q=before_header

I've deployed the patch for testing purposes and here's a few examples of diff from different modules that work:
- copy : https://api.trunk.demo.recordsansible.org/results/436292.html
- ini_file: https://api.trunk.demo.recordsansible.org/results/436183.html
- yum_repository: https://api.trunk.demo.recordsansible.org/results/429161.html
- apt_repository: https://api.trunk.demo.recordsansible.org/results/434723.html
- replace: https://api.trunk.demo.recordsansible.org/results/430522.html
- cron: https://api.trunk.demo.recordsansible.org/results/436130.html
- authorized_keys: https://api.trunk.demo.recordsansible.org/results/430359.html

And then a list of modules for which it doesn't work yet but I think we can support:
- file: https://api.trunk.demo.recordsansible.org/results/436276.html (doesn't provide before_header/after_header)
- lineinfile: https://api.trunk.demo.recordsansible.org/results/436139.html (list of dicts)
- blockinfile: https://api.trunk.demo.recordsansible.org/results/423376.html (list of dicts)

There are also modules that provide another diff format, making it trickier to support:
- config_template (from [openstack-ansible](https://github.com/openstack/ansible-config_template)): https://api.trunk.demo.recordsansible.org/results/435741.html

I've already made it so the ones that don't work at least don't raise an error 500 even if just to troubleshoot but I think it would be a good first iteration to land it once file, lineinfile and blockinfile are working. I haven't spotted other errors for now but I'll continue looking :)

**Comment by dmsimard** [comment]
I fixed ``lineinfile`` and ``blockinfile``. Will look at file later.

**Comment by dmsimard** [comment]
Got the file module working too despite it's custom format:
![Screenshot from 2021-01-14 09-22-43](https://user-images.githubusercontent.com/1291204/104603084-13853e00-564a-11eb-91b8-71b2c41a64d3.png)

I'll continue reviewing and check if I haven't missed anything but this is almost ready to land.

**Comment by vincentbernat** [comment]
Great! Thanks!

**Comment by rptaylor** [comment]
This is very nice, it would be very convenient with a feature like this: https://github.com/ansible/ansible/issues/82445
