### ISSUE TITLE
/api/v1/results much slower than the other API endpoints in browsable API interfaces

### ISSUE THREAD

**Issue by hille721** [ansible-community/ara#323]
## What is the issue ?
The `/api/v1/results` endpoint is much slower than the other ones. In a browser I'm running again and again in 502 - Bad Gateway Errors.

Here a comparison with Google networkanalysis:
 `/api/v1/tasks` (total ~400,000 tasks): ~1s
  `/api/v1/results` (total ~2,000,000 results): ~8s (and around every second time a gateway error)

By using curl, there is not really a significant difference, thus just a GUI problem.

I'm using ara in container behind a nginx proxy in Openshift. I already created my own image with container optimized gunicorn settings (see #322), which solved the problem a bit. But not totally.

## What should be happening ?
Loading   `/api/v1/results` should not take that long.

**Comment by hille721** [comment]
I already found out, that the performance issue is not because of the request itself, it is really just the rendering. And here also not the rendering of the get result, but the rendering of the POST and PUT forms.

Thus with setting `WRITE_LOGIN_REQUIRED: true` you do not have the problem, but you can't do that by running with a proxy.

**Comment by hille721** [comment]
Cool, I have already found a fix for this issue, in which just the html form in the POST/PUT section is disabled, but you can still post data in raw format via the browseable API: https://stackoverflow.com/questions/18587726/django-rest-framework-slow-browsable-ui-because-of-large-related-table

Following has to be done: https://github.com/hille721/ara/commit/2318605dd56c3b1f9e98714354ac62e8a20baace

Then the form will look like this:
![image](https://user-images.githubusercontent.com/38468371/128544804-8c455281-fd36-436a-a9ee-b3554d242f8a.png)
So no html form anymore.

This fix reduces the loading time in my Dev instace from 18.5 s to 3.5 s!

Will submit a PR

**Comment by dmsimard** [comment]
PR is merged, thanks !
