### ISSUE TITLE
Unable to connect to MySQL with SSL enabled

### ISSUE THREAD

**Issue by pleung-eis** [ansible-community/ara#34]
Unable to connect to MySQL database with SSL enabled.

[exception]
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (9002, 'SSL connection is required. Please specify SSL options and retry.\x00')

Added "ssl" parameter to the connection string but it doesn't appear the value is recognized as a dictionary.  Tried passing in the database via cfg file and environment variable.  Both generate same error message.

[ara]
database = "mysql+pymysql://ara:password@mysqlinstance/ara?ssl={'ca': 'pemfile'}
or
export ARA_DATABASE="mysql+pymysql://ara:password@mysqlinstance/ara?ssl={'ca': 'pemfile'}"

  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 330, in _create_ssl_ctx
    ca = sslp.get('ca')
AttributeError: 'str' object has no attribute 'get'

**Comment by dmsimard** [comment]
Thanks for the report!

I've added a note in #19 to consider testing for SSL as well as cleartext.
According to this [post](https://stackoverflow.com/questions/25785252/how-to-connect-to-mysql-server-with-ssl-from-a-flask-app) it looks like the connection string with SSL enabled should look like this: ``mysql+pymysql://ara:password@mysqlinstance/ara?ssl_ca=pemfile``

Can you try that and let me know if it works ?

**Comment by pleung-eis** [comment]
Thanks for the quick response!  Setting the ssl_ca parameter via  env var instead of ssl worked!
