### ISSUE TITLE
ARA expire command returns no results, despite there being extant expired playbooks in database. 

### ISSUE THREAD

**Issue by ccgthree** [ansible-community/ara#341]
## What is the issue ?

Running `ara expire --confirm` to purge expired playbooks does not seem to work. 

## What should be happening ?

Expired playbooks in database should be purged. 

## ARA Expire Command Output

```
2021-11-24 10:01:43,898 INFO ara.cli.expire: Found 0 objects matching query on /api/v1/playbooks
2021-11-24 10:01:43,971 INFO ara.cli.expire: Found 0 objects matching query on /api/v1/plays
2021-11-24 10:01:44,028 INFO ara.cli.expire: Found 0 objects matching query on /api/v1/tasks
2021-11-24 10:01:44,028 INFO ara.cli.expire: 0 objects expired
```

## Status of Playbook \#27 in Local ARA Database

> Note that playbook \#27 in my database _does_ show as expired. 

```
{
  "id": 27,
  "report": "http://127.0.0.1:8000/playbooks/27.html",
  "controller": "ara.server.address",
  "ansible_version": "2.9.27",
  "status": "expired",
  "path": "/root/.ansible/pull/ara.server.address/local.yml",
  "started": "2021-11-10T14:33:02.108692-06:00",
  "ended": null,
  "duration": null,
  "items": {
    "plays": 13,
    "tasks": 156,
    "results": 155,
    "hosts": 1,
    "files": 36,
    "records": 0
  },
  "labels": [
    {
      "id": 1,
      "name": "check:False"
    },
    {
      "id": 2,
      "name": "tags:all"
    },
    {
      "id": 3,
      "name": "skip_tags:none"
    },
    {
      "id": 11,
      "name": "subset:localhost,ara.server.address,ara,127.0.0.1"
    }
  ],
  "arguments": {
    "version": null,
    "verbosity": 0,
    "ask_pass": false,
    "private_key_file": null,
    "remote_user": null,
    "connection": "local",
    "timeout": 10,
    "ssh_common_args": "",
    "sftp_extra_args": "",
    "scp_extra_args": "",
    "ssh_extra_args": "",
    "force_handlers": false,
    "flush_cache": false,
    "become": false,
    "become_method": "sudo",
    "become_user": null,
    "become_ask_pass": false,
    "tags": [
      "all"
    ],
    "skip_tags": [
      "none"
    ],
    "check": false,
    "syntax": false,
    "diff": false,
    "inventory": [
      "/etc/ansible/hosts"
    ],
    "listhosts": false,
    "subset": "localhost,ara.server.address,ara,127.0.0.1",
    "extra_vars": "Not saved by ARA as configured by 'ignored_arguments'",
    "vault_ids": [],
    "ask_vault_pass": false,
    "vault_password_files": [],
    "forks": 5,
    "module_path": null,
    "listtasks": false,
    "listtags": false,
    "step": false,
    "start_at_task": null,
    "args": [
      "/root/.ansible/pull/ara.server.address/local.yml"
    ]
  }
}
```

**Comment by flowerysong** [comment]
This does not appear to be a bug; that playbook is already expired, it doesn't need to be expired again. Are you perhaps confusing `ara expire` and `ara playbook prune`?

**Comment by ccgthree** [comment]
I absolutely am. Good grief. Thanks for bringing this to my attention.

**Comment by dmsimard** [comment]
Thanks for chiming in @flowerysong :)

Indeed, [ara expire](https://ara.readthedocs.io/en/latest/cli.html#ara-expire) is meant to "forcefully" timeout/expire playbooks that have been in the running state for longer than it should which is probably indicative of a playbook that either crashed or was prematurely interrupted (i.e, CTRL+C).

[ara playbook prune](https://ara.readthedocs.io/en/latest/cli.html#ara-playbook-prune) will delete playbooks (and their results) based on certain criteria including the status so you can do something like this to expire playbooks that expired days ago: ``ara playbook prune --status expired --days 3 --confirm``

**Comment by ccgthree** [comment]
Yep. I'm face palming as I type. I dunno why I conflated the two. 

I've added a cron to prune my expired playbooks every 7 days, giving me a chance to peek at them to see what might have gone wrong during weekly maintenance. 

Thank you both for the speedy response. I'll leave my shame here for the world to see. 🤣

**Comment by dmsimard** [comment]
No worries, thanks for the issue anyway so that we won't end up with something like this :)

![wisdom_of_the_ancients](https://user-images.githubusercontent.com/1291204/143286002-5b858fe2-f189-4aa3-95d7-cd457fc96c22.png)
