### ISSUE TITLE
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12

### ISSUE THREAD

**Issue by module0x90** [ansible-community/ara#344]
## What is the issue ?
My Arch Linux system has recently upgraded Python to version 3.10.
Since then I am getting these warnings:

$HOME/.local/lib/python3.10/site-packages/ara/setup/env.py:21: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.sysconfig import get_python_lib
$HOME/.local/lib/python3.10/site-packages/ara/setup/env.py:21: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  from distutils.sysconfig import get_python_lib

## What should be happening ?
I am happy to ignore those warnings, but any idea this can be fixed please?

**Comment by dmsimard** [comment]
Hey @module0x90 and thanks for the issue.

I don't see a problem replacing distutils.sysconfig by [sysconfig](https://docs.python.org/3/library/sysconfig.html) as suggested by the deprecation notice. It looks like the equivalent for [our usage](https://github.com/ansible-community/ara/blob/master/ara/setup/env.py) would be ``sysconfig.get_path('purelib')``.

I can eventually take care of it if no one gets to it first, it's a good low hanging fruit for a contribution :)

**Comment by module0x90** [comment]
Sorry - and also sorry for the late response. I am not really a proficient Python programmer...
