### ISSUE TITLE
ara_record stucks with MariaDB and Postgresql

### ISSUE THREAD

**Issue by spvolin** [ansible-community/ara#35]
ara_record stucks with MariaDB and Postgresql when running playbook for a few inventory hosts and fork>=2
With fork = 1 ara_record works just fine.
Normaly a user wants this parameter be much >>1!!
So putting it to 1 can not be regarded as a solution. It's only an indication of a problem with DB more mature than SQLite.
It demands more testing of ARA with other DB.

**Comment by spvolin** [comment]
ansible.log with MariaDB:
```
 [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible.plugins.callback./usr/local/lib/python2.7/dist-
packages/ara/plugins/callbacks/log_ara.CallbackModule object at
0x7f9ebac9efd0>): Instance '<Task at 0x7f9eb994ad90>' has been deleted, or its
row is otherwise not present.
```

**Comment by spvolin** [comment]
With Postgresql ara_record plugin stucks without any error or warning.
But some ansible processes are "defunctioned".
```
user  51844  1.3  4.5 378120 93176 pts/4    Sl+  17:29   0:01 /usr/bin/python /usr/bin/ansible-playboo
user  52109  0.0  0.0      0     0 pts/4    Z+   17:29   0:00 [ansible-playboo] <defunct>
user  52110  0.0  0.0      0     0 pts/4    Z+   17:29   0:00 [ansible-playboo] <defunct>
```

**Comment by spvolin** [comment]
To the present moment my recommendations for those who wants to run ARA with other DB than SQLite:
1. To run ara_record smoothly just set fork=1 in ansible.cfg [default] section:
```
[defaults]
forks = 1
```

2. To run web just use gunicorn with ara wsgi module rather than webapp with flask, e.g.:

`gunicorn -w 4 -b 0.0.0.0:8000 ara.wsgi:application`

**Comment by dmsimard** [comment]
Good find. I agree that running with ``forks = 1`` is not an acceptable workaround.

I'll keep this opened to make sure we don't have this problem in 1.0.

**Comment by dmsimard** [comment]
I'm going to close this issue because unless mistaken, this is no longer present in ARA 1.x. Please feel free to open a new issue if you see any problems with the latest release.
