### ISSUE TITLE
Masking/redacting values based on patterns

### ISSUE THREAD

**Issue by jbpratt** [ansible-community/ara#359]
Hi @dmsimard , thank you for your work on this awesome project!

## What is the idea ?

A mechanism to mask or redact information based on a pattern. In my case, we end up posting credentials to an API and this gets captured in the `invocation` of the task. From the execution side, no_log is set but since Ara captures everything, it is still being leaked. In terms of best way to implement this, I really have no clue. I'm used to using the [mask passwords](https://plugins.jenkins.io/mask-passwords/) Jenkins plugin but this may be too clunky with dynaconf.

Part of my issues will be alleviated once I finish deploying nginx in front of the api-server or use the builtin django auth. I completely understand if this is too hairy or something not desired within the project.

Image of desired state:

![2022-02-16_17-30](https://user-images.githubusercontent.com/29494941/154375061-87c283bb-5239-4809-af86-7e11afeb7a3a.png)

**Comment by dmsimard** [comment]
Hey @jbpratt and thanks for the nice words o/

I would say that ``no_log: true`` is the way to do it.

It should redact everything and should look a bit like this: https://demo.recordsansible.org/results/690511.html

![Screenshot from 2022-02-16 21-27-14](https://user-images.githubusercontent.com/1291204/154393016-c51f1ad7-4716-4a76-acd3-c9fad9a33df8.png)

Or like that one: https://demo.recordsansible.org/results/691170.html

![Screenshot from 2022-02-16 21-29-56](https://user-images.githubusercontent.com/1291204/154393181-11fdef58-e7de-46d8-8115-60cafeec18cb.png)

If it actually logs things, I would say that is worthy of a bug and would be interested in how to reproduce it.

**Comment by jbpratt** [comment]
Hey @dmsimard , thank you for the info. My apologies, I realize I didn't have `no_log` set on this task. This should resolve things :smile_cat: thanks for your time!
