### ISSUE TITLE
Provide standalone packages for the API, the clients and the plugins

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#36]
``ara-server``, ``ara-plugins`` and ``ara-clients`` were standalone packages on PyPi before we pulled everything back into a single repository in order to simplify things and reduce the overhead from managing multiple repositories.

If possible, it would be relevant to provide standalone packages so that users don't end up installing things they don't need.

It's worth noting that ARA 1.0 is already far more lightweight than 0.x in terms of dependencies and as a result I don't see this as a blocker right now.

20 packages for 1.0a4:
```
ara==1.0.0.0a4
certifi==2019.3.9
chardet==3.0.4
Click==7.0
Django==2.2
django-cors-headers==2.5.3
django-filter==2.1.0
djangorestframework==3.9.3
dynaconf==2.0.2
idna==2.8
pbr==5.2.0
python-box==3.4.0
python-dotenv==0.10.1
pytz==2019.1
PyYAML==5.1
requests==2.21.0
sqlparse==0.3.0
toml==0.10.0
urllib3==1.24.2
whitenoise==4.1.2
```

65 packages for 0.16.3:
```
alembic==1.0.10
ansible==2.7.10
ara==0.16.3
asn1crypto==0.24.0
attrs==19.1.0
Babel==2.6.0
bcrypt==3.1.6
cffi==1.12.3
Click==7.0
cliff==2.14.1
cmd2==0.9.12
colorama==0.4.1
cryptography==2.6.1
debtcollector==1.21.0
extras==1.0.0
fixtures==3.0.0
Flask==1.0.2
Flask-Migrate==2.4.0
Flask-Script==2.0.6
Flask-SQLAlchemy==2.4.0
Frozen-Flask==0.15
iso8601==0.1.12
itsdangerous==1.1.0
Jinja2==2.10.1
junit-xml==1.8
linecache2==1.0.0
Mako==1.0.9
MarkupSafe==1.1.1
msgpack==0.6.1
netaddr==0.7.19
netifaces==0.10.9
oslo.i18n==3.23.1
oslo.serialization==2.29.0
oslo.utils==3.41.0
paramiko==2.4.2
pbr==5.2.0
prettytable==0.7.2
pyasn1==0.4.5
pycparser==2.19
pyfakefs==3.5.8
Pygments==2.3.1
PyNaCl==1.3.0
pyparsing==2.4.0
pyperclip==1.7.0
python-dateutil==2.8.0
python-editor==1.0.4
python-mimeparse==1.6.0
python-subunit==1.3.0
pytz==2019.1
PyYAML==5.1
six==1.12.0
SQLAlchemy==1.3.3
stevedore==1.30.1
testtools==2.3.0
traceback2==1.4.0
unittest2==1.1.0
wcwidth==0.1.7
Werkzeug==0.15.2
wrapt==1.11.1
XStatic==1.0.2
XStatic-Bootstrap-SCSS==3.3.7.1
XStatic-DataTables==1.10.15.1
XStatic-jQuery==3.3.1.1
XStatic-Patternfly==3.21.0.1
XStatic-Patternfly-Bootstrap-Treeview==2.1.3.2
```

**Comment by apollo13** [comment]
What we could do is provide extras, ie one could install "ara[server]" which would then install the full dependencies. Per default I think it should be client/plugins only? You can see an example of this approach in Django https://github.com/django/django/blob/master/setup.py#L87-L90 where we install extra packages for password hashers as needed.

**Comment by apollo13** [comment]
Just to clarify: I'd still go with one ara package because we do not have much code as it is in ara itself -- the current alpha wheel has 64k… But with the extras approach we can disable installation of uneeded requirements (essentially Django if the http client is used).

**Comment by dmsimard** [comment]
@apollo13 that is another approach I didn't think about, thanks for bringing it up.

With the server dependencies taken out, the only required dependencies end up being only ``pbr`` and ``requests``. We're left with an even smaller list:
```
ara==1.0.0.0a5.dev2
certifi==2019.3.9
chardet==3.0.4
idna==2.8
pbr==5.2.0
requests==2.21.0
urllib3==1.24.2
```

It would lead our quickstart install to be ``pip install ara[server]`` instead of ``pip install ara`` and docs would need to be updated appropriately to point this out.

We would probably need to handle django import exceptions in the offline client and tell users about this in a friendly way too.

I'll take a stab at it to see what it would look like.

**Comment by dmsimard** [comment]
Sent a review: https://review.opendev.org/#/c/656950/

**Comment by dmsimard** [comment]
Fixed !
