### ISSUE TITLE
Unable to make distributed sqlite work as expected in the docs

### ISSUE THREAD

**Issue by Alvaro-Campesino** [ansible-community/ara#365]
## What is the issue ?
do 
I am configuring ARA to use distributed sqlite, but it does not matter how i tried, the paths do not answer anything different from a 400 error and i am unable to see the data sent. On the ara docker image logs I get:

```

2022-03-16 11:53:18,984 WARNING django.request: Not Found: /1/ara-report/api/v1/playbooks
172.17.0.4 - - [16/Mar/2022:11:53:18 +0000] "POST /1/ara-report/api/v1/playbooks HTTP/1.1" 404 77 "-" "ara-http-client_1.5.7" 

```
 
In order to do so I am running the image: recordsansible/ara-api:latest 
I have mounted two volumes:
 * `/opt/ara`
 * `/var/www/logs/` 

This is my settings.yaml file inside `/opt/ara`:

```

default:
  ALLOWED_HOSTS:
  - ::1
  - 127.0.0.1
  - localhost
  - 172.17.0.3 
  BASE_DIR: /opt/ara
  CORS_ORIGIN_ALLOW_ALL: false
  CORS_ORIGIN_REGEX_WHITELIST: []
  CORS_ORIGIN_WHITELIST:
  - http://127.0.0.1:8000
  - http://localhost:3000
  - http://172.17.0.3:8000
  DATABASE_CONN_MAX_AGE: 0
  DATABASE_ENGINE: ara.server.db.backends.distributed_sqlite
#  DATABASE_ENGINE: django.db.backends.sqlite3
  DATABASE_HOST: null
  #  DATABASE_NAME: /opt/ara/ansible.sqlite
  DATABASE_OPTIONS: {}
  DATABASE_PASSWORD: null
  DATABASE_PORT: null
  DATABASE_USER: null
  DEBUG: false
  DISTRIBUTED_SQLITE: true
  DISTRIBUTED_SQLITE_PREFIX: ara-report
  DISTRIBUTED_SQLITE_ROOT: /var/www/logs
  EXTERNAL_AUTH: false
  LOGGING:
    disable_existing_loggers: false
    formatters:
      normal:
        format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: normal
        level: INFO
        stream: ext://sys.stdout
    loggers:
      ara:
        handlers:
        - console
        level: INFO
        propagate: 0
    root:
      handlers:
      - console
      level: INFO
    version: 1
  LOG_LEVEL: INFO
  PAGE_SIZE: 100
  READ_LOGIN_REQUIRED: false
  SECRET_KEY: DEfjoAYEuXVwAEaI1gXZX133Hbapcx0KXPUtMuvxZD7tLqpyN8
  TIME_ZONE: Etc/UTC
  WRITE_LOGIN_REQUIRED: false

```
I commented the DABASE_NAME and changed the DATABASE_ENGINE vaules (as seen the original ones), but i keep having the same failure result.

On the other hand, this is my ansible.cfg file:

```

[defaults]
timeout = 30
fact_caching = jsonfile
fact_caching_connection = /tmp/facts_cache
fact_caching_timeout = 7200
forks = 30
gathering = smart
any_errors_fatal = true
callback_whitelist = keos_profile_roles, timer, ara
# Use the YAML callback plugin.
#stdout_callback = yaml
inventory = /stratio/ansible/inventory
roles_path = /stratio/ansible/roles:/stratio/ansible/playbooks/kubespray/roles
collections_paths = /stratio/ansible/collections
deprecation_warnings=False
# https://github.com/ansible/ansible/issues/56930 (to ignore group names with - and .)
force_valid_group_names = ignore
lookup_plugins=~/.ansible/plugins/lookup:/usr/share/ansible/plugins/lookup:/root/.local/lib/python3.9/site-packages/ara/plugins/lookup
callback_plugins=~/.ansible/plugins/callback:/usr/share/ansible/plugins/callback:/root/.local/lib/python3.9/site-packages/ara/plugins/callback
action_plugins=~/.ansible/plugins/action:/usr/share/ansible/plugins/action:/root/.local/lib/python3.9/site-packages/ara/plugins/action

[ssh_connection]
retries = 3
pipelining = true
ssh_args = -o ControlMaster=auto -o ControlPersist=30m

[privilege_escalation]
become = true

[ara]
api_client=http
api_server=http://172.17.0.3:8000/1/ara-report

```

If i change the `api_server` to justo the container base url and port (`http://172.17.0.3:8000`) it will work but not in a distributed way

## What should be happening ?

I am expecting to see the information stored in a new database placed under `/var/www/log/1/ara-report` and see it in the web interface under http://172.17.0.3:8000/1/ara-report

I have tried to copy the database from `/opt/ara/ansible.sqlite` to `/var/www/log/1/ara-report/ansible.sqlite` without a succesfull outcome.

It seems to me i may not be understanding properly the docs. If the files are not automatically created when the callback plugin calls for first time. ¿have i to create them? ¿Should i be able to just copy a sqlite database from a non distributed environment inot a distributed one?

**Comment by dmsimard** [comment]
Hi @Alvaro-Campesino and thanks for the issue.

> Should i be able to just copy a sqlite database from a non distributed environment inot a distributed one?

This is correct and in fact, the backend is explicitly meant to be read-only (as to avoid arbitrary writes for security purposes):
https://github.com/ansible-community/ara/blob/a50abb8605f00b2ef7f382646e61069aed16e206/ara/server/wsgi.py#L52-L54

The intended use case for the distributed sqlite backend is indeed to "host" databases that ara recorded from anywhere.

For example, in the context of CI, this could mean that each job (in jenkins, rundeck or whatever) runs an ansible playbook with ara installed and enabled while saving the results locally with the default sqlite backend. For this part you need to install the ara server dependencies (i.e, ``pip install ara[server]``) but running a server is not required with the default offline client.

Once the job ends, the sqlite database can be uploaded to a server where the distributed backend is enabled and it can be served dynamically based on the URL it was uploaded to.

Hope this helps, let me know if you have any questions.

**Comment by Alvaro-Campesino** [comment]
Ok, then I am not understanding what is happening in my environment. Maybe you can assist @dmsimard 


I am unable to open the databases under `/var/www/logs` that contains the `ansible.sqlite` file that was created when running the playbook locally I only can open the empty database created by the container during startup inside the `/opt/ara` folder.

This is what i have insdie my Docker container running ara:

```
[root@c16f4e7323db /]# ls -l opt/ara/
total 296
-rw-r--r-- 1 root root 299008 Mar 22 15:58 ansible.sqlite
-rw-r--r-- 1 1001 1001   1578 Mar 22 13:59 settings.yaml
[root@c16f4e7323db /]# cat opt/ara/settings.yaml 
---
# This is a default settings template generated by ARA.
# To use a settings file such as this one, you need to export the
# ARA_SETTINGS environment variable like so:
#   $ export ARA_SETTINGS="/opt/ara/settings.yaml"

default:
  ALLOWED_HOSTS:
  - ::1
  - 127.0.0.1
  - localhost
  - 172.17.0.3 
  BASE_DIR: /opt/ara
  CORS_ORIGIN_ALLOW_ALL: false
  CORS_ORIGIN_REGEX_WHITELIST: []
  CORS_ORIGIN_WHITELIST:
  - http://127.0.0.1:8000
  - http://localhost:3000
  - http://172.17.0.3:8000
  DATABASE_CONN_MAX_AGE: 0
  DATABASE_ENGINE: ara.server.db.backends.distributed_sqlite
#  DATABASE_ENGINE: django.db.backends.sqlite3
  DATABASE_HOST: null
  #  DATABASE_NAME: /opt/ara/ansible.sqlite
  DATABASE_OPTIONS: {}
  DATABASE_PASSWORD: null
  DATABASE_PORT: null
  DATABASE_USER: null
  DEBUG: false
  DISTRIBUTED_SQLITE: true
  DISTRIBUTED_SQLITE_PREFIX: ara-report
  DISTRIBUTED_SQLITE_ROOT: /var/www/logs
  EXTERNAL_AUTH: false
  LOGGING:
    disable_existing_loggers: false
    formatters:
      normal:
        format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: normal
        level: DEBUG
        stream: ext://sys.stdout
    loggers:
      ara:
        handlers:
        - console
        level: DEBUG
        propagate: 0
    root:
      handlers:
      - console
      level: DEBUG
    version: 1
  LOG_LEVEL: INFO
  PAGE_SIZE: 100
  READ_LOGIN_REQUIRED: false
  SECRET_KEY: DEfjoAYEuXVwAEaI1gXZX1wZHbapcx0KXPUtMuvxZD7tLqpyN8
  TIME_ZONE: Etc/UTC
  WRITE_LOGIN_REQUIRED: false
[root@c16f4e7323db /]# ls -l /var/www/logs
total 8
drwxrwxr-x 3 1001 1001 4096 Mar 16 07:54 env
drwxrwxr-x 3 1001 1001 4096 Mar 22 15:53 vagrant
[root@c16f4e7323db /]# ls -l /var/www/logs/vagrant/
total 4
drwxrwxr-x 2 1001 1001 4096 Mar 22 15:55 ara-report
[root@c16f4e7323db /]# ls -l /var/www/logs/vagrant/ara-report/
total 368
-rw-r--r-- 1 root root 368640 Mar 22 15:55 ansible.sqlite
-rw-r--r-- 1 root root   1491 Mar 22 15:54 settings.yaml
[root@c16f4e7323db /]# 

```

My final desired picture is to have different `ansible.sqlite` files mapped into the docker container and to be able to query them using the url: http://<ip_address>:<port>/<environment_name>/ara-report and get the info. Instead this is what I get:

![image](https://user-images.githubusercontent.com/57360851/159524591-1b81a398-5b36-494e-a848-d5d772122d83.png)

It is weird that I can see the info of the new database it created in `/opt/ara` which is obviusly empty.?

**Comment by dmsimard** [comment]
Hi @Alvaro-Campesino, I missed the fact that you are running ara from a container image.

If you look at the [container image build definition](https://github.com/ansible-community/ara/blob/2e7d507e0bbe8f04441cb43cf5117aef09656234/contrib/container-images/fedora-pypi.sh#L16), the start command is:
``/usr/local/bin/ara-manage migrate && /usr/bin/gunicorn-3 --workers=4 --access-logfile - --bind 0.0.0.0:8000 ara.server.wsgi`` which is actually suitable for any database backend except for distributed sqlite.

On top of setting DATABASE_ENGINE to ``ara.server.db.backends.distributed_sqlite`` and DISTRIBUTED_SQLITE to ``true``, it also requires a different WSGI application -- ``ara.server.wsgi`` is insufficient and I was able to reproduce your issue that way.

If you want to continue using the container image, you need to supply a slightly different command. I did it with podman but it should be the same for Docker:
```
podman run --name ara --detach --tty \
  --volume ~/.ara/server:/opt/ara:z \
  --volume /root/www:/var/www:z \
  -p 8000:8000 \
  quay.io/recordsansible/ara-api:latest \
  /usr/bin/gunicorn-3 --workers=4 --access-logfile - --bind 0.0.0.0:8000 ara.server.wsgi:distributed_sqlite
```

The command above doesn't include ``ara-manage migrate`` because it's unnecessary when using the distributed sqlite backend.

I was able to make it work with the container image after starting it with the right command.

Let me know if that works,

Thanks.

**Comment by Alvaro-Campesino** [comment]
Thanks very much, that solves it.
