### ISSUE TITLE
isort UserWarning

### ISSUE THREAD

**Issue by hille721** [ansible-community/ara#423]
## What is the issue ?

Following warnings appear in `isort` section when running `tox -e linters`

```
/home/hille/gitrepos/ara/.tox/linters/lib/python3.9/site-packages/isort/main.py:1261: UserWarning: W0501: The following deprecated CLI flags were used and ignored: --recursive!
  warn(
/home/hille/gitrepos/ara/.tox/linters/lib/python3.9/site-packages/isort/main.py:1265: UserWarning: W0500: Please see the 5.0.0 Upgrade guide: https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0.html
  warn(
```

This is also visible in the last zuul pipeline runs, e.g. https://ansible.softwarefactory-project.io/zuul/build/790363697e2942a3b8f02d427d1f0a1a/console

Will provide a PR to fix this issue following the upgrade guide (https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0.html)

**Comment by dmsimard** [comment]
Merged the PR, thanks @hille721 !
