### ISSUE TITLE
Make controller hostname and username recording optional

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#425]
## What is the idea ?

Recording the controller hostname and username has privacy implications and users may want to opt out of recording them.

There should be callback settings (somewhat like ``IGNORED_FILES``) that disables recording for them and sets their value to None instead.

**Comment by amilcarlucas** [comment]
This is nice. But using ara 1.5.8 I do not see the "user that run the playbook" nowhere in the web interface. Where is it?

**Comment by hille721** [comment]
new feature which will come with the 1.6.0 release.
There is already a release candidate available to test: https://pypi.org/project/ara/1.6.0.0rc1

**Comment by hille721** [comment]
@dmsimard I think this issue can be closed because #438 is already merged

**Comment by dmsimard** [comment]
Yes indeed, thanks @hille721.

Sorry about the delay in releasing 1.6.0. It is overdue.
