### ISSUE TITLE
ansible_user undefined variable on gunicorn-task

### ISSUE THREAD

**Issue by rndmh3ro** [ansible-community/ara#44]
# Problem

Installing ara on Ubuntu 18.04 with: 
```bash
> ubuntu:~/ara-1.0.0b1/playbooks$ cat hosts
127.0.0.1
> ansible-playbook -i hosts ara_web.yaml -K
```

fails with: 

```bash
TASK [ara_api : Install gunicorn] ************************************************************************************
ok: [127.0.0.1]

TASK [ara_api : Set up systemd unit file for gunicorn to run the ARA API] ********************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible_user' is undefined"}

PLAY RECAP ***********************************************************************************************************
127.0.0.1                  : ok=25   changed=1    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

```

# Resolution

One also could either define `ansible_user` as a variable or use `ansible_user_id` in the gunicorn service-template.

# Additional data

ARA-release: `1.0.0b1`

OS:
```
VERSION="18.04.2 LTS (Bionic Beaver)"
```

Python:
```
ubuntu:~/ara-1.0.0b1/playbooks$ python --version
Python 2.7.15rc1
ubuntu:~/ara-1.0.0b1/playbooks$ which python
/usr/bin/python
```

**Comment by dmsimard** [comment]
@rndmh3ro thanks for this report !

You're right, ``ansible_user`` is not necessarily always defined and it looks like ``ansible_user_id`` is what we want and have available from the Ansible facts.

This will be fixed by https://review.opendev.org/660414 and will be part of beta2.

**Comment by dmsimard** [comment]
This is fixed by https://github.com/ansible-community/ara/commit/79c7e1b5e37b7cd7335083ce162d07be35b42741

Closing the issue, thanks again for the report.
