### ISSUE TITLE
Docker image tag related to git tags

### ISSUE THREAD

**Issue by StephaneG31** [ansible-community/ara#449]
I'm supprised there's no official docker image tags (like for the 1.5.8).

see https://hub.docker.com/r/recordsansible/ara-api

To have only stable image, do I need to build myself the image ?

**Comment by hille721** [comment]
There are already discussions about that in following issue: https://github.com/ansible-community/ara/issues/352

**Comment by StephaneG31** [comment]
> There are already discussions about that in following issue: #352

Thanks I subscribe to this issue and close mine.
