### ISSUE TITLE
Host tab only showing 1 host which is the most recent host to run a playbook.

### ISSUE THREAD

**Issue by d3al** [ansible-community/ara#484]
## What is the issue ?

Host tab shows the most recent host to run a playbook and never shows more than 1 record. I noticed this happened on 1.6.0. Just upgraded to 1.6.1 and the issue still exists. I don't know if this issue always existed on this installation or if it's a recent change.

Ara is installed via docker image.

Tasks, playbook tabs are populating and retaining historical records.

## What should be happening ?

Host tab should show all hosts.

**Comment by dmsimard** [comment]
Hey @d3al and thanks for the issue.

You're correct, the hosts tab shows the most recent playbook for every host by default.

In the search options there is a checkbox ``Include all playbook reports`` which should then display every playbook for every host.

Can you try it and let me know if it is the behavior you are looking for ?

**Comment by d3al** [comment]
That resolved the issue, thank you.
