### ISSUE TITLE
Slow loading of tasks in ara 0.x web interface

### ISSUE THREAD

**Issue by biohazd** [ansible-community/ara#51]
Hi

When I click on a TASK and then onto an entry on the "status" column, it takes ages to load. I have the same setup on an older version of ARA and its much faster.

Database in stored in AWS RDS.

Versions.
ara (0.16.4)
ansible (2.5.5)

**Comment by dmsimard** [comment]
@biohazd The performance and memory requirements for running the web interface in ARA 0.x is somewhat of a known issue.

There has been attempts in the past to try and address some of it like https://github.com/ansible-community/ara/commit/ea1e0b6e815c02373b2fe6ddb96cbaa214fad308 and https://github.com/ansible-community/ara/commit/5e03143e55b702c841e8b3904b7efd1d762ae517 but ultimately, the actual design of how the components are coupled together is flawed.

Both the backend and the frontend have been re-written from scratch in ara 1.0 (which has just been [released](https://ara.recordsansible.org/blog/2019/06/04/announcing-the-release-of-ara-records-ansible-1.0/)). The web interface is now decoupled and only requests what it needs from the API which should scale far much better.

If someone comes up with a patch that addresses performance in 0.x and it's a fairly low hanging fruit, I would accept it but if it's a significant chunk of code, I would rather we move on to 1.0 instead.

**Comment by biohazd** [comment]
ahh ok, thanks.
