### ISSUE TITLE
AWX/TOWER label with tower_project_revision

### ISSUE THREAD

**Issue by cerberek** [ansible-community/ara#519]
## What is the idea ?
- related to AWX/TOWER plays
- add possiblity to add label with `tower_project_revision`
- to see in ARA GUI/playbooks API label with commit hash

**Comment by dmsimard** [comment]
In the documentation there is an example using ara_record to attach a git commit revision to a playbook here: https://ara.readthedocs.io/en/latest/ansible-plugins-and-use-cases.html#ara-record-arbitrary-key-values-in-playbook-reports

It's not exactly the same as a playbook label but without knowing more about your use case, I don't know whether that would work for you or if you really want a label.

Let me know if that works.

**Comment by cerberek** [comment]
Label would be more usefull as you can see it on Playbooks view and I'm able to filter by it.

Good to know that something like this is possible. I was able add this record with commit revision.
But label would be still better

**Comment by dmsimard** [comment]
I don't have an AWX environment available to test with right now but there's different ways to set labels: https://ara.readthedocs.io/en/latest/ansible-plugins-and-use-cases.html?highlight=label#playbook-names-and-labels

I believed that it would be possible to use something like this:
```
- name: a play
  hosts: localhost
  vars:
    ara_playbook_labels:
      - "{{ lookup('pipe', 'git rev-parse HEAD' }}"
  tasks:
    # ... 
```
but I remembered about this issue: https://github.com/ansible-community/ara/issues/180

![Screenshot from 2023-09-28 22-22-15](https://github.com/ansible-community/ara/assets/1291204/f3bd655a-c6ac-41c7-81f7-63d5eb2c715b)

In essence, when ara recovers the variables from ansible, their values are not templated so we get the raw text instead.

Unless someone wants to try and get that working, I see two alternatives. I'm not sure if if it would work with AWX but it might give you ideas:
- You can set labels with an extra-var, on the CLI it could be something like this:
```bash
ansible-playbook -i hosts playbook.yaml -e ara_playbook_labels="commit:$(git rev-parse HEAD)"
```
- You can set an environment variable for the AWX jobs somehow. ara will recover both ``ARA_PLAYBOOK_LABELS`` and ``ARA_DEFAULT_LABELS`` and use them to set labels.

**Comment by cerberek** [comment]
Ok,  if templating would works,  this `ara_playbook_labels` would be exactly what I was asking for.

I started following templating issue if it will be solved. For now I'm adding labels to env before running ansible-playbook.
But this solution doesn't work for AWX. So for AWX for time being there will be at least this record with commit revision.

Closing issue.
Thanks for help
