### ISSUE TITLE
stylesheet after upgrade 1.6.1 => 1.7.0

### ISSUE THREAD

**Issue by christianwohlgemuth** [ansible-community/ara#520]
## What is the issue ?

after upgrade ara from 1.6.1 to 1.7.0 i think is missing a css file. a screenshot of the GUI id here => https://pasteboard.co/yhunjbpXd4gh.jpg

**Comment by hille721** [comment]
I think that's how the new design looks like. There are also some explanations about the new UI in the blog: https://ara.recordsansible.org/blog/2023/09/12/announcing-the-release-of-ara-1.7.0/#a-refresh-for-the-ui

**Comment by christianwohlgemuth** [comment]
yes, it seems to be the new design.

What I don't understand is that the title says "A refresh for the UI" and then the text says "nd links are blue like in the 1990's." :-)
