### ISSUE TITLE
ARA_RECORD_USER_NAME and ARA_RECORD_CONTROLLER_NAME not working

### ISSUE THREAD

**Issue by rptaylor** [ansible-community/ara#529]
Related to https://github.com/ansible-community/ara/issues/493  https://github.com/ansible-community/ara/pull/507

## What is the issue ?

In my ansible environment (root user in a podman container) I set
```
export ARA_RECORD_USER_NAME=testuser
export ARA_RECORD_CONTROLLER_NAME=testnode
```
and then I run an ansible play. It gets recorded in Ara but the user is still blank and the controller name is still the hostname of the container.

Am I missing something?

## What should be happening ?

The user and controller name should be filled in based on the values set in the env vars.

**Comment by rptaylor** [comment]
![Pasted image](https://github.com/ansible-community/ara/assets/1686627/24853326-90c4-4417-867a-36dea282aef4)

**Comment by dmsimard** [comment]
Hi @rptaylor, thanks for the issue.

A question to clarify: where is Ansible (and the ara callback plugin) running relative to the container and the ara server ?

The environment variables should be set where Ansible is running from, they are not used by the server.

**Comment by rptaylor** [comment]
Hi @dmsimard thanks for looking.
Yes it is set in the same place as ANSIBLE_CALLBACK_PLUGINS, ARA_API_SERVER etc where ansible runs in the container  environment.

**Comment by rptaylor** [comment]
I also tried `ARA_RECORD_USER=true` but that did not help.

Hmm I have 
```
python3-ara-1.5.7-5.fc37.noarch
ara-1.5.7-5.fc37.noarch
```
maybe that is too old?

**Comment by rptaylor** [comment]
But ara isn't available anymore in Fedora 38 or 39 it seems ...  :/
There is only the ara-doc package.

**Comment by rptaylor** [comment]
That is confusing, `dnf info ara` returns "Error: No matching Packages to list" but if you `dnf install ara` it installs python3-ara as an alias, which apparently still includes the ARA CLI.

Anyway I updated to python3-ara-1.7.0-1.fc38.noarch and now it works!  Sorry for the noise.
