### ISSUE TITLE
Cleanup or TTL

### ISSUE THREAD

**Issue by sspreitzer** [ansible-community/ara#530]
## What is the idea ?

I would love to see a cleanup feature, where records older a certain date or fulfilling a certain criteria can be cleaned up, removed from the database.

Another feature could be to assign a TTL to records, so they get removed automatically.

**Comment by flowerysong** [comment]
https://ara.readthedocs.io/en/latest/cli.html#ara-playbook-prune

**Comment by sspreitzer** [comment]
@flowerysong thank you, will close #530 the issue
