### ISSUE TITLE
ara.recordsansible.org cert needs to be renewed

### ISSUE THREAD

**Issue by cognifloyd** [ansible-community/ara#531]
## What is the issue ?
The Let's Encrypt TLS cert on ara.recordsansible.org has expired as of Sunday, December 24, 2023 at 5:55:22 PM.

So, the zscaler internet filter on my work laptop is blocking the site now.

## What should be happening ?
Cert is valid allowing me to access the website.

**Comment by dmsimard** [comment]
Hi @cognifloyd and thanks for the issue.

The certbot cron renewal was failing, I've fixed it and the certificate is renewed.

**Comment by wgordon17** [comment]
@dmsimard Looks like there's another failing cronjob 😞

**Comment by dmsimard** [comment]
It was something else this time but it's renewed, thanks!
