### ISSUE TITLE
Callback errors with ARA server behind secured reverse proxy

### ISSUE THREAD

**Issue by lcrownover** [ansible-community/ara#532]
## What is the issue ?

Hello,

My nodes are all RHEL8, running python3.9 in a venv, latest ansible and ARA (installed via pip). I'm getting the following error when trying to run a playbook:

```
[WARNING]: Failure using method (v2_playbook_on_start) in callback plugin
(<ansible.plugins.callback.ara_default.CallbackModule object at
0x15145fe755e0>): Expecting value: line 1 column 1 (char 0)
[WARNING]: Failure using method (v2_playbook_on_play_start) in callback plugin
(<ansible.plugins.callback.ara_default.CallbackModule object at
0x15145fe755e0>): 'NoneType' object is not subscriptable
[WARNING]: Failure using method (v2_playbook_on_task_start) in callback plugin
(<ansible.plugins.callback.ara_default.CallbackModule object at
0x15145fe755e0>): 'NoneType' object is not subscriptable
```

This was working previously when I had had my ARA server exposed, but it doesn't seem to work with my ARA server being behind an LDAP-secured reverse proxy. 

apache configuration
```
ServerName myserver

  # Configure SSL
  SSLEngine on
  SSLCertificateFile /etc/pki/tls/certs/myserver.crt
  SSLCertificateKeyFile /etc/pki/tls/private/myserver.key

  # These were pulled from the default ssl.conf that we deleted
  ErrorLog logs/ssl_error_log
  TransferLog logs/ssl_access_log
  LogLevel warn
  CustomLog logs/ssl_request_log \
          "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"

  #----------------------------------------------------------------------------#
  #  Ansible Reporting
  #----------------------------------------------------------------------------#
  ProxyPass /ara http://127.0.0.1:8000/ara
  ProxyPassReverse /ara http://127.0.0.1:8000/ara

  <Location /ara>
    AuthName "Privileged access"
    AuthType Basic
    AuthBasicProvider ldap
    LDAPReferrals Off
    AuthLDAPURL "correct working server"
    AuthLDAPBindDN "auth account"
    AuthLDAPBindPassword "auth password"
    AuthLDAPGroupAttributeIsDN On
    <RequireAll>
      Require valid-user
      Require ldap-filter memberof:1.2.840.113556.1.4.1941:=DN of auth group
    </RequireAll>
  </Location>
```

ara server settings.yaml
```
default:
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - myfqdn
    - myshortname
  BASE_PATH: /ara
  EXTERNAL_AUTH: true
  READ_LOGIN_REQUIRED: false
  WRITE_LOGIN_REQUIRED: false
```

I can successfully log into the web interface using an account in the specified LDAP group, so I know that authentication is working.

client config
```
[ara]
api_client = http
api_server = https://myserver/ara
api_username = this account works
api_password = password
api_insecure = true
```

Ansible should be set up correctly:

```
$ env | grep ANS
ANSIBLE_ACTION_PLUGINS=/opt/ansible/venv/lib/python3.9/site-packages/ara/plugins/action
ANSIBLE_LOOKUP_PLUGINS=/opt/ansible/venv/lib/python3.9/site-packages/ara/plugins/lookup
ANSIBLE_CALLBACK_PLUGINS=/opt/ansible/venv/lib/python3.9/site-packages/ara/plugins/callback
```

I tried setting:

```
ARA_LOG_LEVEL=DEBUG
ARA_DEBUG=true
```

and running the playbook with `-vvv`, but ARA doesn't give me anything more verbose.

Would you have any guidance on how to troubleshoot this issue?

Thanks!

**Comment by dmsimard** [comment]
Hi @lcrownover and thanks for the issue.

There are some general troubleshooting tips in the docs here: https://ara.readthedocs.io/en/latest/troubleshooting.html

I am not super familiar with ldap authentication and setting ara under a different base path but I don't think these are an issue if you are able to use them properly.

Running ``ansible-playbook -vvv`` should at least provide the full python exception tracebacks which are otherwise "eaten" by Ansible. Could you provide these ?

Also, since you are running RHEL, could you confirm whether you have Ansible (or ansible-core) installed via a dnf/yum package ? In other words: are you positive that the ansible command that runs is executed from the venv where ara is installed ?

Could you provide a ``pip freeze`` from the venv ?

Thanks.

**Comment by lcrownover** [comment]
Hey @dmsimard, thanks for the reply. I'm not sure what I did but it seems to be mysteriously working now... Maybe I had something extra that was causing issues and our nightly `ansible-pull` might have cleared it out.
