### ISSUE TITLE
ARA_API_SERVER tries port 443 with a k8s ingress address forwarding to 8000

### ISSUE THREAD

**Issue by fleetvonr** [ansible-community/ara#536]
## What is the issue ?

About my environment:
- K8s deployment (service, ingress, pvc, deployment) with the latest `recordsansible/ara-api:latest` image.
- Only changed settings from default are ALLOWED_HOST where I added the ingress hostname and TIME_ZONE

By opening the ingress address without the port the ui is displayed, ingress port forwards to 8000.
But inside my ansible pipelines I cannot only add the ingress url:
ara tries to connect to port 8000 and when I add the port 8000 to the ingress url it fails.

https://myingress.host.xy:8000
```
[WARNING]: Failure using method (v2_playbook_on_start) in callback plugin
(<ansible.plugins.callback.ara_default.CallbackModule object at
0x7f870cf2c410>): HTTPSConnectionPool(host='myingress.host.xy',
port=8000): Max retries exceeded with url: /api/v1/playbooks (Caused by
SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number
(_ssl.c:1006)')))
```

https://myingress.host.xy
```
[WARNING]: Failure using method (v2_playbook_on_start) in callback plugin
(<ansible.plugins.callback.ara_default.CallbackModule object at
0x7f25e801e7d0>): HTTPSConnectionPool(host='myiingress.host.xy',port=443):
Max retries exceeded with url: /api/v1/playbooks (Caused by
ConnectTimeoutError
```
```
k describe ing ara
Name:             ara
Labels:           <none>
Namespace:        [namespace]
Address:          [ip]
Ingress Class:    nginx
Default backend:  <default>
TLS:
  SNI routes myingress.host.xy
Rules:
  Host                    Path  Backends
  ----                    ----  --------
  myingress.host.xy
                             ara-service:8000 ([ip]:8000)
```

## What should be happening ?

Ara should either be able to recognize that this url will port forward to 8000 or it would be nice if the PORT could be specified in another ARA_API_SERVER_PORT variable.

**Comment by dmsimard** [comment]
Hi and thanks for the issue.

I'm not sure what is going on here. The callback (and CLI) are expected to respect whatever the value of ``ARA_API_SERVER`` is.

To be clear, where is your ara server reachable on and what is the value of ``ARA_API_SERVER`` ? They should be the same along with ``ARA_API_CLIENT=http``.

The port can (and should) be included into the value of ``ARA_API_SERVER`` if there is one. There is no need for an additional setting for it.

**Comment by fleetvonr** [comment]
The value of `ARA_API_SERVER` is my ingress host that forwards HTTP/S traffic to port 8000.
And as far as I know (I can ask someone from the k8s team), ingress can/should/is (?) not used with a port, which poses a problem now because if I add only the ingress address to the ARA_API_SERVER it will use 443 as port and if I specify 8000 it fails also.

**Comment by fleetvonr** [comment]
So I'm back and I got it fixed.
I have a NodePort configured now and it works with that :)
