### ISSUE TITLE
Ara v1.0 feaure list

### ISSUE THREAD

**Issue by biohazd** [ansible-community/ara#54]
Hi

>> Ara v1.0 is not feature complete yet

Do you have a list of features that work in Ara v1.0 as compared to the latest v0.xx ?

What features are still missing from Ara v1.0?

**Comment by dmsimard** [comment]
@biohazd there is no such list at this time. What particular feature or use case are you interested in ?
There is already a list of issues here on GitHub, some of which is for new feature work. If you feel something is missing, feel free to contribute 👍

**Comment by biohazd** [comment]
thanks.   Is v1 ready for production use and by that I mean it works without crashing or erroring?

**Comment by dmsimard** [comment]
@biohazd v1 was released ready for use.
Each new patch is unit and integration tested against different versions of Ansible and on different linux distributions.

I'm not aware of any crashes or serious errors at this time. If any are encountered, please open an issue about them.

**Comment by biohazd** [comment]
do you have a demo or video of the new V1 release anywhere?

**Comment by dmsimard** [comment]
@biohazd yes, see the readme here: https://github.com/ansible-community/ara/blob/master/README.rst#live-demos

**Comment by biohazd** [comment]
briliant thanks, it looks great.  Is that demo the latest version or is it bit older and new features have been released but are not in that demo ?

**Comment by biohazd** [comment]
for example. there is no search,  you cant order the headings (for example "status") and it doesnt show the output of each play.

**Comment by dmsimard** [comment]
I'm happy that you are interested in ARA but GitHub issues are meant for bug and feature tracking. 
I will try to clarify this in the README and will close this issue for now.

It would be helpful if you could hop on [IRC or Slack](https://ara.recordsansible.org/community/) for general questions.

The live demos are currently up to date and ara-web has it's own issue tracking here: https://github.com/ansible-community/ara-web/issues

As you can tell, we are still iterating on ara-web and could use your help to implement some missing features.

Please feel free to create issues if you find bugs or have ideas for new features.

Thanks !
