### ISSUE TITLE
"Duration" column on the playbook view page doesn't sort

### ISSUE THREAD

**Issue by evgeni** [ansible-community/ara#543]
## What is the issue ?

1. go to https://demo.recordsansible.org/playbooks/3991.html
2. click on the duration column to sort by duration
3. expect the table to be sorted by duration now, while it is not

## What should be happening ?

It should sort ;-)

Refs: https://chaos.social/@zhenech/112355188740814889

**Comment by dmsimard** [comment]
I looked and the button is there as intended: https://github.com/ansible-community/ara/blob/c750fcd5a7e62f0b9087c05f219c9f8ba6d7dbf9/ara/ui/templates/partials/tables/playbook_results.html#L31

When comparing it to the playbook list table that works, I notice that the ``<form>`` is there: https://github.com/ansible-community/ara/blob/c750fcd5a7e62f0b9087c05f219c9f8ba6d7dbf9/ara/ui/templates/partials/tables/playbooks.html#L16-L18

While it's missing for the task table. That's probably the issue.

**Comment by dmsimard** [comment]
The sort by date field has the same issue as well.

**Comment by dmsimard** [comment]
@evgeni https://github.com/ansible-community/ara/pull/544 works for me and should fix it.

Thanks for the issue :)

**Comment by evgeni** [comment]
FWIW, it works for me too now :)
