### ISSUE TITLE
How to authenticate a client to a proxy webserver (nginx with basic auth enabled)?

### ISSUE THREAD

**Issue by d3al** [ansible-community/ara#554]
## What is the issue ?
I read over the docs about authentication as I need to protect the UI so I setup a new ara server via docker image and installed nginx to proxy, created a basic nginx config with basic authentication. This is working if I hit the ara server via browser I do see the ara UI.

I updated ara settings files to accept authenticated requests.

  EXTERNAL_AUTH: true
  READ_LOGIN_REQUIRED: false
  WRITE_LOGIN_REQUIRED: false

On the client side I've modified a working call to add in username/password variables. Client is not able to authenticate while running the ansible job.

ARA_API_USERNAME
ARA_API_PASSWORD

ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)" ARA_API_USERNAME=user ARA_API_PASSWORD=password ARA_API_CLIENT="http" ARA_API_SERVER="https://xyz.abc" ansible-pull --full -f -U git_repo_url.git local.yml

The job runs but there are errors, from the callback, nothing is pushed to the ara server. I think I'm close but I must be missing something.

**Comment by dmsimard** [comment]
Hi @d3al, it seems you ended up figuring it out ?

For the benefit of future readers would you like to explaib what was the issue ?

Thanks!

![wisdom_of_the_ancients](https://github.com/ansible-community/ara/assets/1291204/c96d4c4f-1dc9-45e8-a923-e9d35879a44d)
