### ISSUE TITLE
missing wheel dependencie fir ARA 1.0 with API server 

### ISSUE THREAD

**Issue by JSGUYOT** [ansible-community/ara#56]
Hi ! 

It seem dependencies missing for install ara[server] with pip ==> wheel is missing

Best regards,

**Comment by dmsimard** [comment]
@JSGUYOT can you provide more details and a trace ? What operating system and architecture ?
There is a wheel package for ara up on PyPi: https://pypi.org/project/ara/#files

**Comment by JSGUYOT** [comment]
Hi !

I Think, i remember it's on Ubuntu 18.04, in Python3 perhaps with PIP3.
I should remake à test. 

Regards

**Comment by dmsimard** [comment]
@JSGUYOT have you found a way to reproduce the issue ?

**Comment by JSGUYOT** [comment]
Hi !


Not for now, sorry, I'm on vacation :)
I look at this when I return.

Regards, 

----- Mail original -----
De: "David Moreau Simard" <notifications@github.com>
À: "ansible-community/ara" <ara@noreply.github.com>
Cc: "JSGUYOT" <jeansebastien.guyot@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Mardi 2 Juillet 2019 21:25:40
Objet: Re: [ansible-community/ara] missing wheel dependencie fir ARA 1.0 with API server  (#56)



@JSGUYOT have you found a way to reproduce the issue ?

**Comment by dmsimard** [comment]
@JSGUYOT I'll close this for now, please re-open with more information if you are able to reproduce the problem.
