### ISSUE TITLE
database: size of plays.uuid

### ISSUE THREAD

**Issue by philfry** [ansible-community/ara#562]
Hi,

I'm using ara 1.7.1 together with ansible 2.16.9 and a mysql backend on Fedora 40 (both server and client).

I found that ara is failing on POSTing to /api/v1/plays at start with
```
Failed to post on /api/v1/plays: {'name': 'myhost.example', 'status': 'running', 'uuid': 'b428bc6b-38da-40a3-bdb3-aa7de32644d3', 'playbook': 1, 'started': '2024-08-12T13:11:48.835955+00:00'}
[WARNING]: Failure using method (v2_playbook_on_play_start) in callback plugin (<ansible.plugins.callback.ara_default.CallbackModule object at 0x7fc2b5d3bfb0>): Expecting value: line 1 column 1 (char 0)
```
as it gets a 500 from the ara server. The server complains that the provided data for `uuid` was too long – and indeed, it is. The uuid provided by the client is 36 chars – see https://github.com/ansible-community/ara/blob/e7ee252a147f99ce45ccdd7267a61741526542f5/ara/plugins/callback/ara_default.py#L524

The `uuid` column in the database is 32 chars, which come from Django, see

https://github.com/django/django/blob/228128618bd895ecad235d2215f4ad4e3232595d/django/db/models/fields/__init__.py#L2732

Is there anything wrong with changing the corresponding line?
```diff
--- ara_default.py.orig	2024-01-22 01:00:00.000000000 +0100
+++ ara_default.py	2024-08-12 15:34:58.683241258 +0200
@@ -521,7 +521,7 @@ class CallbackModule(CallbackBase):
             "/api/v1/plays",
             name=play.name,
             status="running",
-            uuid=play._uuid[:36],
+            uuid=play._uuid.replace('-', '')[:32],
             playbook=self.playbook["id"],
             started=datetime.datetime.now(datetime.timezone.utc).isoformat(),
         )
```

**Comment by dmsimard** [comment]
Hi and thanks for the issue.

I revisited https://github.com/ansible-community/ara/issues/211 which is where we initially found out that UUIDs provided could be too long and 36 characters seemed to be good at the time.

I can spend some time soon to double check whether that is the case.

In the meantime, could you confirm the version of django you are running with ? Thanks!

**Comment by flowerysong** [comment]
Truncating to 32 characters would not work. The most common presentation form of a UUID is 36 characters (it's broken up with hyphens to make it more readable), and this should be translated by Django into a string of the correct length:
```
>>> import uuid
>>> u_str = 'b428bc6b-38da-40a3-bdb3-aa7de32644d3'
>>> u_obj = uuid.UUID(u_str)
>>> u_obj.hex
'b428bc6b38da40a3bdb3aa7de32644d3'
>>> len(u_obj.hex)
32
```
Truncating the input string to 32 characters will just break things:
```
>>> uuid.UUID(u_str[:32])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/uuid.py", line 178, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
```

**Comment by philfry** [comment]
Thanks for your replies.

> In the meantime, could you confirm the version of django you are running with ? Thanks!

sure. It's Django 4.2.14

**Comment by philfry** [comment]
> Truncating to 32 characters would not work. The most common presentation form of a UUID is 36 characters (it's broken up with hyphens to make it more readable), and this should be translated by Django into a string of the correct length:
> 
> ```
> >>> import uuid
> >>> u_str = 'b428bc6b-38da-40a3-bdb3-aa7de32644d3'
> >>> u_obj = uuid.UUID(u_str)
> >>> u_obj.hex
> 'b428bc6b38da40a3bdb3aa7de32644d3'
> >>> len(u_obj.hex)
> 32
> ```
> 
> Truncating the input string to 32 characters will just break things:
> 
> ```
> >>> uuid.UUID(u_str[:32])
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python3.11/uuid.py", line 178, in __init__
>     raise ValueError('badly formed hexadecimal UUID string')
> ValueError: badly formed hexadecimal UUID string
> ```

I think I might have expressed myself incorrectly. Following your example this would work fine, imho.

```
>>> import uuid
>>> my_uuid = str(uuid.uuid4())
>>> my_uuid
'd4353795-53cd-443e-983a-67a65852314d'
>>> u_str = my_uuid.replace('-', '')
>>> u_str
'd435379553cd443e983a67a65852314d'
>>> u_obj = uuid.UUID(u_str)
>>> u_obj
UUID('d4353795-53cd-443e-983a-67a65852314d')
>>> u_obj.hex
'd435379553cd443e983a67a65852314d'
```

**Comment by flowerysong** [comment]
It might work, but you haven't demonstrated why it's necessary. Django will accept UUIDs in the normal format.

**Comment by philfry** [comment]
Maybe it's a Django issue or something else, I don't know. That's why I'm asking for support.

Django created the database itself (ara-manage migrate) and decided that the uuid column is 32 chars big (see my links above). If ara sends a 36 char representation of a 127 bit / 32 digit uuid and neither ara nor Django cares to convert it to 32 chars, this probably won't fit and leads to the error message mentioned in my OP.

The funny thing is, when running the ara server on an OracleLinux 9 with Django 4.2.10 and ara 1.7.1, while the client runs ara 1.7.1 on Fedora 40 I don't have these problems. Even though the uuid is still passed in human readable form (36 chars) from the callback plugin, Django (server) saves the complete and correct uuid without the dashes to the database (32 chars).

I guess I'll need some more investigation before I can give a reasonable followup to this issue.

**Comment by philfry** [comment]
I was unable to reproduce this on another machine and after reinstalling the virtenv the issue was gone.
Sorry for the noise!
