### ISSUE TITLE
"latest" Docker image is not up to date with ara 1.7.2

### ISSUE THREAD

**Issue by Skunnyk** [ansible-community/ara#573]
Hi,

Latest docker images https://hub.docker.com/r/recordsansible/ara-api/tags contains Ara `1.7.1` and not Ara `1.7.2`:

```
$ docker run -ti recordsansible/ara-api:fedora39-pypi-latest ara --version
ara 1.7.1
```
```
$ docker inspect recordsansible/ara-api:fedora39-pypi-latest | jq ".[].RepoDigests"
[
  "recordsansible/ara-api@sha256:ad10431beca056140000d501a90fbc8102cf551d896cf02cbef28428300cc393"
]
```

They have been built few days before the 1.7.2 release.

Can you please push an update to the registry ? :angel: Thank you!

**Comment by dmsimard** [comment]
Hi @Skunnyk and thanks for the issue.

You appear to be correct. Something may have gone wrong when publishing and I didn't notice.
Sorry about that.

I will take care of it sometime soon.

**Comment by dmsimard** [comment]
I'm taking the opportunity to update our container images to fedora 40: https://github.com/ansible-community/ara/pull/574

When that PR merges, new builds should go out automatically.

**Comment by dmsimard** [comment]
Hi @Skunnyk, updated images have been built and pushed to both quay.io and docker hub.

I've confirmed that 1.7.2 is truly there this time.

Enjoy and thanks again.

**Comment by Skunnyk** [comment]
Thank you for your work!
