### ISSUE TITLE
setup.cfg does not exists when exporting the callback plugins

### ISSUE THREAD

**Issue by Systemgeek-louis** [ansible-community/ara#575]
Installed ARA locally no issues.  I see it in /root/ara.
When I try to export ANSIBLE_CALLBACK_PLUGINS I get this:
`[root@fm01-main02a ~]# export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)"
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/root/ara/setup.py", line 6, in <module>
    setuptools.setup(setup_requires=["pbr"], pbr=True, long_description_content_type="text/markdown")
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.9/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 437, in __init__
    _Distribution.__init__(self, {
  File "/usr/lib64/python3.9/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 743, in finalize_options
    ep(self)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 750, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/root/.local/lib/python3.9/site-packages/pbr/core.py", line 100, in pbr
    raise errors.DistutilsFileError(
distutils.errors.DistutilsFileError: The setup.cfg file /root/setup.cfg does not exist.`

I am running on Rocky Linux 9.4

**Comment by dmsimard** [comment]
Hi,

Two things:
- How did you install ara ?
- What is in /root/ara? The git repo ?

If you are running the command from inside the /root repository, python will try to look inside the ara folder.

You can try running the command from elsewhere or rename the folder to something like "ara-src" instead and it should work.

It's not so much an ara thing than a python thing.

**Comment by Systemgeek-louis** [comment]
I followed the commands on the github page to install:
Recording playbooks without an API server
ara records to a local sqlite database by default and does not require a persistent server:
# Install ansible (or ansible-core) with ara (including API server dependencies)
python3 -m pip install --user ansible "ara[server]"

# Configure Ansible to enable ara
export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)"

# Run an Ansible playbook as usual
ansible-playbook playbook.yml

# Check out the CLI
ara playbook list
ara host list

# or the UI at http://127.0.0.1:8000
ara-manage runserver

As you suggested I did try changing /root/ara to /root/ara-src and when I export the variable I get:
***@***.*** ~]# export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)"
/usr/bin/python3: Error while finding module specification for 'ara.setup.callback_plugins' (ModuleNotFoundError: No module named 'ara.setup')

I will point out that this worked just fine when my ansible server was Rocky Linux 8 so not sure why it would be having issues now.

I do get that its most likely not an ARA issue but a python issue.  However, I am sure you are much much much more experienced at getting things running with python then I am.

Louis

From: David Moreau Simard ***@***.***>
Date: Tuesday, November 5, 2024 at 13:16
To: ansible-community/ara ***@***.***>
Cc: Louis Bohm ***@***.***>, Author ***@***.***>
Subject: Re: [ansible-community/ara] setup.cfg does not exists when exporting the callback plugins (Issue #575)

Hi,

Two things:
·         How did you install ara ?
·         What is in /root/ara? The git repo ?

If you are running the command from inside the /root repository, python will try to look inside the ara folder.

You can try running the command from elsewhere or rename the folder to something like "ara-src" instead and it should work.

It's not so much an ara thing than a python thing.

**Comment by Systemgeek-louis** [comment]
I was finally able to make it work by deleting /root/ara*.  Then I re-installed with: python3 -m pip install "ara[server]".  Doing this gave no errors when I ran variable export.

I do not know where / why ara was found in /root.  And I am not mistaking the /root/.ara for it.
Louis


From: Louis Bohm ***@***.***>
Date: Tuesday, November 5, 2024 at 14:02
To: ansible-community/ara ***@***.***>, ansible-community/ara ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [ansible-community/ara] setup.cfg does not exists when exporting the callback plugins (Issue #575)
I followed the commands on the github page to install:
Recording playbooks without an API server
ara records to a local sqlite database by default and does not require a persistent server:
# Install ansible (or ansible-core) with ara (including API server dependencies)
python3 -m pip install --user ansible "ara[server]"

# Configure Ansible to enable ara
export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)"

# Run an Ansible playbook as usual
ansible-playbook playbook.yml

# Check out the CLI
ara playbook list
ara host list

# or the UI at http://127.0.0.1:8000
ara-manage runserver

As you suggested I did try changing /root/ara to /root/ara-src and when I export the variable I get:
***@***.*** ~]# export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)"
/usr/bin/python3: Error while finding module specification for 'ara.setup.callback_plugins' (ModuleNotFoundError: No module named 'ara.setup')

I will point out that this worked just fine when my ansible server was Rocky Linux 8 so not sure why it would be having issues now.

I do get that its most likely not an ARA issue but a python issue.  However, I am sure you are much much much more experienced at getting things running with python then I am.

Louis

From: David Moreau Simard ***@***.***>
Date: Tuesday, November 5, 2024 at 13:16
To: ansible-community/ara ***@***.***>
Cc: Louis Bohm ***@***.***>, Author ***@***.***>
Subject: Re: [ansible-community/ara] setup.cfg does not exists when exporting the callback plugins (Issue #575)

Hi,

Two things:
How did you install ara ?
What is in /root/ara? The git repo ?

If you are running the command from inside the /root repository, python will try to look inside the ara folder.

You can try running the command from elsewhere or rename the folder to something like "ara-src" instead and it should work.

It's not so much an ara thing than a python thing.

**Comment by dmsimard** [comment]
It was related to python trying to load from the current directory then.

Thanks for reporting back!
