### ISSUE TITLE
delete old Ansible runs from Ara

### ISSUE THREAD

**Issue by biohazd** [ansible-community/ara#60]
Is there an easy way to delete old data in ARA?   I noticed our has Ansible runs going back to 2017 so I would like to prune the old data and maybe keep a year. I'm also hoping deleting odl data might speed it up abit.

Is there a simple SQL query I can use or even a script ?

**Comment by dmsimard** [comment]
A user implemented a cron to prune data from ARA 0.x: https://github.com/BonnyCI/hoist/commit/8d7822c75202bcb931020329146f418af512f2e1

Going to close this as a duplicate of https://github.com/ansible-community/ara/issues/31, feel free to chime in there if there is anything else.

**Comment by dmsimard** [comment]
@biohazd This is merged and will land in 1.3.0: https://github.com/ansible-community/ara/commit/35aa8826d7bfdf5e43c10ea26a07f51cc66763fc
