### ISSUE TITLE
API: Add support for sorting results

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#68]
## What component is this about ?

API, API clients

## What is the idea ?

When querying the API, we should be able to request a sorted list of results based on different fields, for example:

- Sort by start date
- Sort by end date
- Sort by duration
- Sort by status

django-rest-framework provides filtering and ordering ([docs](https://www.django-rest-framework.org/api-guide/filtering/#orderingfilter)) but we should also consider whether or not we need to implement things at the django model level like suggested in https://github.com/ansible-community/ara/pull/66.

**Comment by dmsimard** [comment]
@guillaumevincent, @apollo13: Do you have an opinion on how we should do this ?

**Comment by guillaumevincent** [comment]
does https://www.django-rest-framework.org/api-guide/filtering/#orderingfilter is enough for you?

**Comment by dmsimard** [comment]
@guillaumevincent I briefly discussed this with @Turgon37 in his pull request but he mentions concerns:

> 1, I've not seen any database index on column other than primary keys, so I can suppose the sort will be expensive to the RDBMS on ara installations with amount of records.
> 2. I've performed some test with Django viewset and I'm notice that the sort is performed by the code not by the database. In fact, by using the model's "ordering" attribute the sort is performed with the ORDER BY SQL clause.

**Comment by guillaumevincent** [comment]
IIRC ordering filter is performed by the database https://www.django-rest-framework.org/api-guide/filtering/#orderingfilter
It should be enough for now

Create the index if you need it

**Comment by apollo13** [comment]
> Create the index if you need it

That.

>  2. I've performed some test with Django viewset and I'm notice that the sort is performed by the code not by the database. In fact, by using the model's "ordering" attribute the sort is performed with the ORDER BY SQL clause.

I strongly doubt that, sorting is generally performed in the db by django/drf. Btw I would not use the models `ordering` attribute at all since that will force every query to be ordered. This can be expensive for joins etc…

**Comment by dmsimard** [comment]
WIP: https://review.opendev.org/#/c/693067/
