### ISSUE TITLE
Wrong playbook execution time

### ISSUE THREAD

**Issue by yannfill** [ansible-community/ara#69]
I have installed ARA using the playbooks provided and everything is fine, except that the execution time is wrong. I have added `TIME_ZONE: Europe/Paris` in ARA API settings.yaml and it seems that the start time taken into account is in GMT whereas the end time is in local time. ARA API server and the computer playing the playbook are set up in the same french timezone.
![Screenshot_2019-09-06 ARA Records Ansible](https://user-images.githubusercontent.com/11028416/64416435-77334a80-d097-11e9-83ca-8361e8d1687a.png)
![Screenshot_2019-09-06 https ara-api ecritel net](https://user-images.githubusercontent.com/11028416/64416445-7c909500-d097-11e9-9397-4aea73fc519b.png)

**Comment by dmsimard** [comment]
@yannfill Hi and thanks for the report !

@turgeon37 has thankfully submitted a fix for that issue and it should be landing in the master branch soon: https://review.opendev.org/#/c/678348/

**Comment by dmsimard** [comment]
Somewhat related, I found an issue relating to the callback and the API server using different time zones: https://review.opendev.org/#/c/683218/

**Comment by dmsimard** [comment]
I believe this is fixed in the upcoming release of 1.2.0. Please feel free to re-open if it isn't the case.

**Comment by yannfill** [comment]
Hi,

I just installed ara from master and while it seems fine on the ara-api web view:
![ara-api](https://user-images.githubusercontent.com/11028416/71114447-1b1cae00-21d0-11ea-8cee-e8ea2a3ed554.png)
I got this on the ara-web side:
![ARA Records Ansible](https://user-images.githubusercontent.com/11028416/71114501-37b8e600-21d0-11ea-80d2-6aeecc30fcdc.png)

**Comment by dmsimard** [comment]
@yannfill good catch! Would you like to create an issue in [ara-web](https://github.com/ansible-community/ara-web/issues) about it ?
ara-web is unfortunately lagging behind and I could use some help.
