### ISSUE TITLE
An Ansible collection for ARA

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara#71]
Ansible is moving forward with an approach called *Ansible collections*, see "[The Future of Ansible Content Delivery](https://www.ansible.com/blog/the-future-of-ansible-content-delivery)".

ARA has a lot of Ansible content and it might be worthwhile to consider packaging everything in an Ansible collection:
- [Action and callback plugins](https://github.com/ansible-community/ara/tree/master/ara/plugins)
- [Roles](https://github.com/ansible-community/ara/tree/master/roles)
- [Playbooks](https://github.com/ansible-community/ara/tree/master/playbooks)
- [Integration tests](https://github.com/ansible-community/ara/tree/master/tests/integration)

Docs:
- User guide: https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/user_guide/collections_using.rst
- Dev guide: https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/dev_guide/developing_collections.rst

Let's use this issue to discuss how we might do this.

**Comment by rndmh3ro** [comment]
I played around with ansible-collections and ara, see this PR for the code:
I tested this with Ansible 2.10.0.dev0 on Ubuntu 18.04 and python 3.7:

```
> pwd
/root/dev/ara

# add galaxy.yml to root of repo
echo > galaxy.yml

# write a test using the collection
echo > collection_with_defaults.yaml

# build the collection
> ansible-galaxy collection build .

# install the collection
> ansible-galaxy collection install ara-ara-1.0.0.tar.gz

# run test in collection
> ansible-playbook /home/user/.ansible/collections/ansible_collections/ara/ara/tests/collection_with_defaults.yaml
```

After installing ara with this test, I could open the frontend and see my playbook-runs.

One thing one has to think about is where to place the ara-plugins. The collections-spec says plugins should live in a folder next to the `galaxy.yml`-file. However as the plugins aren't used *during* the playbook-run but later installed (correct me if I'm wrong), one could argue that the place where they are right now is fine.

**Comment by rndmh3ro** [comment]
> With that said, I think the best option is probably to leave the plugins outside of the collection.
Our collection on galaxy would only contain the roles (ara_api, ara_web, etc) and these would take care of installing ara and it's dependencies.

Good idea!

> If we go down this route, we need to add support in the roles to configure Ansible itself to use ara. Configuring Ansible would probably be the easy part -- maybe as simple as an ini_file task to set the callback_plugins and action_plugins parameters in ~/.ansible.cfg.

IMO configuring the ansible.cfg to use ara is a good idea. Maybe the user can specify which ansible.cfg should be changed and which python-interpreter is used (there's probably a fact for this). This should be optional, of course.

**Comment by dmsimard** [comment]
Ping @gundalow @gregdek: is it okay to use the ansible-community namespace in Galaxy to publish roles and collections ?

**Comment by gundalow** [comment]
> Ping @gundalow @gregdek: is it okay to use the ansible-community namespace in Galaxy to publish roles and collections ?

We are currently discussing what the namespaces will look like and how they will be managed. 
Could you please remind me about this in a week?

**Comment by dmsimard** [comment]
@gundalow sure, no rush. Thanks for looking into this.

**Comment by dmsimard** [comment]
@gundalow apologies, I know it's been a while but were you able to figure out if we should use the ansible-community namespace on Galaxy ? Thanks !

**Comment by gundalow** [comment]
Hi,
You can use the `community` namespace in Galaxy.

**Comment by dmsimard** [comment]
@gundalow how does that work in practice ? Is there documentation about it or is there already a project set up to use it ?

**Comment by Thulium-Drake** [comment]
I did some testing by trying to import the repo on galaxy-dev, there's a few things that need fixing:

1. The roles and the repo itself require markdown documentation (rst files aren't recognized fully, see link)
2. Some warnings need to be fixed (see log below)
3. If you want to deploy the plugins, they need to be symlinked to the root of the repo.

```
Starting import: task_id=86861, artifact_id=86875 
Getting doc strings via ansible-doc 
Finding content inside collection 
Loading role ara_api 
Linting role ara_api via ansible-lint... 
tasks/database_engine/django.db.backends.mysql.yaml:34: [E204] Lines should be no longer than 160 chars 
tasks/database_engine/django.db.backends.mysql.yaml:45: [E301] Commands should not change things if nothing needs doing 
tasks/database_engine/django.db.backends.postgresql.yaml:34: [E204] Lines should be no longer than 160 chars 
tasks/database_engine/django.db.backends.postgresql.yaml:45: [E301] Commands should not change things if nothing needs doing 
tasks/database_engine/django.db.backends.sqlite3.yaml:25: [E301] Commands should not change things if nothing needs doing 
ara_api/tasks/pre-requirements.yaml:64: [E204] Lines should be no longer than 160 chars 
Loading role ara_web 
Linting role ara_web via ansible-lint... 
tasks/install/source.yaml:102: [E303] rsync used in place of synchronize module 
ara_web/tasks/nodejs.yaml:45: [E204] Lines should be no longer than 160 chars 
Loading role ara_frontend_nginx 
Could not get role description, no role metadata found 
Linting role ara_frontend_nginx via ansible-lint... 
Loading action ara_playbook 
Linting action ara_playbook via flake8... 
Loading action ara_record 
Linting action ara_record via flake8... 
Loading callback ara_default 
Linting callback ara_default via flake8... 
Loading lookup ara_api 
Linting lookup ara_api via flake8... 
Collection validation and loading complete 
Processing via galaxy-importer complete 
Checking dependencies in importer data 
Publishing collection 
Collection published 
Import completed with 9 warnings and 0 errors 
```
The end results: https://galaxy-dev.ansible.com/thulium_drake/ara_test

With regards to deploying the plugins, for visibility it might be useful to actually do deploy them via the collection. Is there a way for the modules to produce a userfriendly error when they are called without the modules being present?

Then you could 'just' install the collection, but if you try to call the modules without the required python libs it'll tell you to install them :-)

**Comment by dmsimard** [comment]
The server does some validation on dependencies before trying to start: https://github.com/ansible-community/ara/blob/master/ara/server/__main__.py

The callback currently relies on the API clients to do this kind of validation, for example: https://github.com/ansible-community/ara/blob/master/ara/clients/offline.py#L28

The problem is that although you can "install" plugins through collections, there is no way to express python dependencies.

So a collection just for the roles themselves is simple but getting the plugins to work without those python dependencies isn't as straightforward.

**Comment by dmsimard** [comment]
I kind of replied quickly, more on this:

> I did some testing by trying to import the repo on galaxy-dev, there's a few things that need fixing:
>     1. The roles and the repo itself require markdown documentation (rst files aren't recognized fully, see link)

Good catch, the docs (including the README) are in rst format which makes it easy to include in the documentation with sphinx. I've asked about whether there are any plans for Galaxy to support RST rendering but haven't had an answer yet.

>     2. Some warnings need to be fixed (see log below)

Yes, perhaps ironically, although the roles are integration tested, they aren't linted :(
Adding an ansible-lint CI job wouldn't be complicated, just haven't done it yet.

>     3. If you want to deploy the plugins, they need to be symlinked to the root of the repo.

It'd be hard to ship plugins in the collection as per my previous reply. Not impossible but not convenient. I would love to be proven wrong !

> The end results: https://galaxy-dev.ansible.com/thulium_drake/ara_test

So how did this work in practice ? Did you set up a standalone repository with the roles in them ?
I'm debating moving the existing roles into a new repository meant for the collection.

> With regards to deploying the plugins, for visibility it might be useful to actually do deploy them via the collection. Is there a way for the modules to produce a userfriendly error when they are called without the required python libs being present?
> 
> Then you could 'just' install the collection, but if you try to call the modules without the required python libs it'll tell you to install them :-)

One of the things that has come up earlier in this issue would be to ship a role which would take care of the Ansible plugins configuration -- the existing ara_api role isn't a good fit, it's really oriented for the API server.

Maybe an "ara_plugins" role that installs the base ara package and then configures ansible.cfg with the right things. Then, you would install the collection, include the role and after that the playbooks would be recorded.

**Comment by Thulium-Drake** [comment]
> I kind of replied quickly, more on this:
> 
> > ```
> > 1. The roles and the repo itself require markdown documentation (rst files aren't recognized fully, see link)
> > ```
> 
> Good catch, the docs (including the README) are in rst format which makes it easy to include in the documentation with sphinx. I've asked about whether there are any plans for Galaxy to support RST rendering but haven't had an answer yet.

Fair enough, there's 2 ways out of this, either add markdown docs, or ask the galaxy guys to support rst :-)
> 
> > ```
> > 2. Some warnings need to be fixed (see log below)
> > ```
> 
> Yes, perhaps ironically, although the roles are integration tested, they aren't linted :(
> Adding an ansible-lint CI job wouldn't be complicated, just haven't done it yet.
> 
> > ```
> > 3. If you want to deploy the plugins, they need to be symlinked to the root of the repo.
> > ```
> 
> It'd be hard to ship plugins in the collection as per my previous reply. Not impossible but not convenient. I would love to be proven wrong !

Agreed, it's very inconvenient due to the fact you need extra python libs, but putting all that in it's own role might elegantly solve that problem!

> 
> > The end results: https://galaxy-dev.ansible.com/thulium_drake/ara_test
> 
> So how did this work in practice ? Did you set up a standalone repository with the roles in them ?
> I'm debating moving the existing roles into a new repository meant for the collection.
> 
So what I did was:

0. ```mkdir /tmp/collection_skel && ansible-galaxy collection init thulium_drake.ara_test```
1. Clone the repo as is
2. ```touch README.md``` in the repo and all the roles
3. Copy /tmp/collection_skel/galaxy.yml to the git checkout
4. Symlink ```./ara/plugins``` to ```./plugins```
5. ```ansible-galaxy collection build```
6. ```ansible-galaxy collection publish --api-key $(sed 's/token: //' ~/.ansible_galaxy_dev)  -s  https://galaxy-dev.ansible.com thulium_drake-ara_test-1.0.0.tar.gz```

> > With regards to deploying the plugins, for visibility it might be useful to actually do deploy them via the collection. Is there a way for the modules to produce a userfriendly error when they are called without the required python libs being present?
> > Then you could 'just' install the collection, but if you try to call the modules without the required python libs it'll tell you to install them :-)
> 
> One of the things that has come up earlier in this issue would be to ship a role which would take care of the Ansible plugins configuration -- the existing ara_api role isn't a good fit, it's really oriented for the API server.
> 
> Maybe an "ara_plugins" role that installs the base ara package and then configures ansible.cfg with the right things. Then, you would install the collection, include the role and after that the playbooks would be recorded.

Agreed, that sounds like the best solution to me, all the other roles mostly work on their own (and do completely if you don't need an external DB)

I'll try some things in a test repo :-)

**Comment by Thulium-Drake** [comment]
I have setup a repo which can be cloned and published to Galaxy, but the role for setting up Ansible still needs to be written.

Repo: https://github.com/Thulium-Drake/ara_collection
Galaxy page: https://galaxy-dev.ansible.com/thulium_drake/ara_collection (still waiting for the import to complete)

I'll try to work out a role to install the python stuff required to run the modules

P.S. if the repo turns out to be a good fit, I'll transfer it :-)

**Comment by dmsimard** [comment]
> Repo: https://github.com/Thulium-Drake/ara_collection
> Galaxy page: https://galaxy-dev.ansible.com/thulium_drake/ara_collection (still waiting for the import to complete)

:+1: 

> I'll try to work out a role to install the python stuff required to run the modules

Ok, happy to review, thanks for working on this!

> P.S. if the repo turns out to be a good fit, I'll transfer it :-)

Thinking out loud, there's going to be a few things to consider when we move the roles out:

1) We need to keep the git history for the roles because.. well, it would be a shame to lose the history. I've done this kind of thing before, can be tricky but worth it.

2) Adjust documentation because we won't be able to do relative includes anymore so they're shown at places like [here](https://ara.readthedocs.io/en/latest/ansible-role-ara-api.html). We can take this opportunity to re-write the READMEs in markdown and we can link to them from the ARA main docs.

3) Adjust the CI jobs which rely on roles to install and configure things for the sake of testing the roles and ara itself. This shouldn't be complicated, we just assume that the roles are there right now so we'd just need to install the collection before running tests. Zuul should allow us iterate on this easily without needing to merge or break anything. The good news is we can already start testing this ahead of time with the test collection you've submitted. If all the tests pass, we know we've done a good job :tada:

4) Update the live demo playbook to use the collection instead: https://github.com/ansible-community/ara-infra/blob/master/playbooks/live-demo.yaml

5) I suspect that **removing** the roles from the repo might end up breaking people who have been using them and I'd like to avoid that if we can help it. The roles are part of the tagged releases even though they're not part of the python package. I'd probably tag a release, deprecate them and then truly remove them. It would mean the roles would temporarily live in two different places for a little bit.

I'm not leaving all of that up to you of course and I can help or do any of the above. I'll start with # 3.

**Comment by dmsimard** [comment]
> Galaxy page: https://galaxy-dev.ansible.com/thulium_drake/ara_collection (still waiting for the import to complete)

Yeah, looks like it's 404'ing still.

I took another look at [thulium_drake.ara_test](https://galaxy-dev.ansible.com/thulium_drake/ara_test) and it has the following note about collections:
![Screenshot from 2020-05-10 12-27-24](https://user-images.githubusercontent.com/1291204/81504893-d2b67780-92b9-11ea-9bfe-d6fc7075db53.png)

It's worth considering that Ansible 2.8 is going to be supported for [quite a bit](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html) still but I suppose moving to a new repository will not make things worse, only a different repository.

**Comment by dmsimard** [comment]
Started a WIP here: https://review.opendev.org/#/c/726644/

For now I've removed the roles files completely so we can be sure to test the right roles out of the collection repository once it's setup in Zuul. I'm not sure which would have precedence if both are in the role path with the same name ? TBD.

**Comment by Thulium-Drake** [comment]
I have updated my repo again after I took the git-equivalent of a couple of hacksaws and chisels to it. :-) (gave me an interesting look in how to chop up repo's and the wonders of sed)

It's supposed to have all the relevant history of the roles and the plugins (I left the playbooks in there, those prolly have to be reworked after this is done)

I'll reply on the other messages with quotes.

**Comment by Thulium-Drake** [comment]
> > Repo: https://github.com/Thulium-Drake/ara_collection
> > Galaxy page: https://galaxy-dev.ansible.com/thulium_drake/ara_collection (still waiting for the import to complete)
> 
> +1
> 
> > I'll try to work out a role to install the python stuff required to run the modules
> 
> Ok, happy to review, thanks for working on this!
> 
> > P.S. if the repo turns out to be a good fit, I'll transfer it :-)
> 
> Thinking out loud, there's going to be a few things to consider when we move the roles out:
> 
>     1. We need to keep the git history for the roles because.. well, it would be a shame to lose the history. I've done this kind of thing before, can be tricky but worth it.

Gotcha, makes sense, I think my hacksaw trick worked, check it out :-)

> 
>     2. Adjust documentation because we won't be able to do relative includes anymore so they're shown at places like [here](https://ara.readthedocs.io/en/latest/ansible-role-ara-api.html). We can take this opportunity to re-write the READMEs in markdown and we can link to them from the ARA main docs.
> 

Agreed, I think just rendering the normal docs into markdown can even be a good start, just shave off the stuff that isn't required.

>     3. Adjust the CI jobs which rely on roles to install and configure things for the sake of testing the roles and ara itself. This shouldn't be complicated, we just assume that the roles are there right now so we'd just need to install the collection before running tests. Zuul should allow us iterate on this easily without needing to merge or break anything. The good news is we can already start testing this ahead of time with the test collection you've submitted. If all the tests pass, we know we've done a good job tada
> 

Sounds cool! I'm not familair with Zuul at all (I use Drone CI myself in combination with Molecule)

>     4. Update the live demo playbook to use the collection instead: https://github.com/ansible-community/ara-infra/blob/master/playbooks/live-demo.yaml

I can take a look at that, I still have my playbook for installing the whole enchilada on my Debian server. But where shall I stash the work in progress in the meantime?

> 
>     5. I suspect that **removing** the roles from the repo might end up breaking people who have been using them and I'd like to avoid that if we can help it. The roles are part of the tagged releases even though they're not part of the python package. I'd probably tag a release, deprecate them and then truly remove them. It would mean the roles would temporarily live in two different places for a little bit.
> 

Agreed, let's try not breaking things when we don't really have to. And my guess would be that the roles would be mostly identical anyway. And IIRC you can copy over commits to other repo's, right?

>     6. Set up the code review infrastructure and CI for the new repository, we can even add ansible-lint :p
> 

Awesome! :-)

> 
> I'm not leaving all of that up to you of course and I can help or do any of the above. I'll start with # 3.

**Comment by Thulium-Drake** [comment]
> Started a WIP here: https://review.opendev.org/#/c/726644/
> 
> For now I've removed the roles files completely so we can be sure to test the right roles out of the collection repository once it's setup in Zuul. I'm not sure which would have precedence if both are in the role path with the same name ? TBD.

AFAIK, you use collections by their FQCN (namespace.collection.role), so the roles should not collide.

**Comment by Thulium-Drake** [comment]
I have updated my repository with the initial version of the ARA client role.

It works, but it requires the use of some scripting (I place some stuff in /usr/local/bin to wrap ARA in the system environment). This is only required when the installation source is git, I will test this later with source = pip.

**Comment by dmsimard** [comment]
I haven't forgotten about this and I'd like to prioritize it. I'm sure it would make the roles more convenient to consume if the roles could be installed easily from galaxy.

Regarding https://github.com/Thulium-Drake/ara_collection, it looks good enough to start with but I would take out the plugins -- they're shipped by installing ara and I think that's okay for now. It also ensures the necessary python dependencies are installed.

I have opinions about the ara_ansible role :)
It works, no doubt :+1: but I also can't help but wonder if someone else has solved the problem of installing and configuring Ansible with Ansible :p

I'd be happy to defer to something external so we don't reinvent wheels for this purpose and more importantly to lessen the maintenance (and testing!) burden. Geerlingguy has a role we could use, perhaps: https://github.com/geerlingguy/ansible-role-ansible

I don't see this as a blocker to setting up the collection, though. I'll make some time to create the code review infrastructure for it soon.

**Comment by Thulium-Drake** [comment]
> I haven't forgotten about this and I'd like to prioritize it. I'm sure it would make the roles more convenient to consume if the roles could be installed easily from galaxy.
> 

No rush! I'm sure there's plenty of work to do :-)
> Regarding https://github.com/Thulium-Drake/ara_collection, it looks good enough to start with but I would take out the plugins -- they're shipped by installing ara and I think that's okay for now. It also ensures the necessary python dependencies are installed.removed all stuff 
> 
Makes sense, even installing ARA (clients) from source should ideally come from the other repo. I have updated the repo to remove them.

Do you want to replicate the changes I did, or can/shall I transfer the repository to you, so you can take it from here?
> I have opinions about the ara_ansible role :)
> It works, no doubt +1 but I also can't help but wonder if someone else has solved the problem of installing and configuring Ansible with Ansible :premoved all stuff 
> 
I've tried to 'just' install the ARA clients and generate a sample config for use with Ansible :-)

I copied the code for installing the API server and changed it to make sure the clients are there.
> I'd be happy to defer to something external so we don't reinvent wheels for this purpose and more importantly to lessen the maintenance (and testing!) burden. Geerlingguy has a role we could use, perhaps: https://github.com/geerlingguy/ansible-role-ansible
> 
Makes sense, sharing is caring :-)
> I don't see this as a blocker to setting up the collection, though. I'll make some time to create the code review infrastructure for it soon.
Nice!

**Comment by dmsimard** [comment]
> Do you want to replicate the changes I did, or can/shall I transfer the repository to you, so you can take it from here?

When we create a project in opendev, we can [specify an upstream to clone from](https://docs.opendev.org/opendev/infra-manual/latest/creators.html#add-the-project-to-the-master-projects-list) or start from scratch.

Happy to start from your repo if you don't mind !
I sent a PR to make it ready for import: https://github.com/Thulium-Drake/ara_collection/pull/1

**Comment by Thulium-Drake** [comment]
Sure thing! I've merged the PR, so we should be good to go!

**Comment by dmsimard** [comment]
@Thulium-Drake I just realized that the commit history contains stuff about the plugins like https://github.com/Thulium-Drake/ara_collection/commit/6b4d5155459097ab3865c4e818233c3dbf7e85cf and I'd love if we could keep those out just to start with a clean history :/

I'd hate to bother you about doing that work again, I'll take a shot at it.

**Comment by dmsimard** [comment]
Ok so here's basically what I did with a flavor inspired by [stackoverflow](https://stackoverflow.com/a/50090278/6072068):
```
git clone https://github.com/ansible-community/ara
cd ara
git remote rm origin

# Remove every file and commit that doesn't involve the roles directory
git filter-branch --subdirectory-filter roles -- --all

# The above moves the roles to the root of the repository, move them back under roles/
git filter-branch -f --index-filter 'git ls-files -s | sed -e "s/\t\"*/&roles\//" |
    GIT_INDEX_FILE=$GIT_INDEX_FILE.new \
        git update-index --index-info &&
 mv "$GIT_INDEX_FILE.new" "$GIT_INDEX_FILE"' HEAD

# Push the results to a new bare repository
git remote add origin https://github.com/dmsimard/ara-collection
git push -u origin master
```

I tried to do something fancier and would had liked to even carry over the initial changes from [ara-infra](https://github.com/ansible-community/ara-infra/commits/master/roles) (these roles have moved around a **lot**!) but in the end there were so many conflicts to manage :p

I think the result is good enough for a first import: https://github.com/dmsimard/ara-collection and I sent a patch to create the project: https://review.opendev.org/735439

**Comment by dmsimard** [comment]
The project is created: https://opendev.org/recordsansible/ara-collection

I'll take care of setting up the remainder of the things like .gitreview, tests and zuul jobs.

**Comment by dmsimard** [comment]
Repository is now mirrored on github: https://github.com/ansible-community/ara-collection

I guess next steps is to setup the galaxy.yml and do an upload to galaxy.

**Comment by dmsimard** [comment]
Ok the upload to galaxy will take a bit more work because it's expecting the READMEs to be in markdown rather than RST. I've put up a WIP patch: https://review.opendev.org/#/c/735700/

**Comment by Thulium-Drake** [comment]
Awesome! Really looking forward to the results!

Anything you need me to do in the mean time? I will clean up the repo's to avoid confusion and you have replicated what we needed anyways :-)

**Comment by dmsimard** [comment]
In a nutshell, I've added a README for the collection, translated the existing READMEs to markdown and the collection is up now: https://galaxy.ansible.com/arecordsansible/ara

Next step is to move the Zuul integration jobs over and I even have some patches I want/need to land in the roles: https://review.opendev.org/#/q/project:recordsansible/ara-collection

**Comment by Thulium-Drake** [comment]
Sweet! I will look into this further tomorrow and try to update my playbooks to use the collection instead of the git checkout I have now. TBC!

**Comment by dmsimard** [comment]
Integration tests import is WIP: https://review.opendev.org/#/c/738946/

**Comment by Thulium-Drake** [comment]
Hmm, is it me or is there a typo in the namespace?
```
current on galaxy: arecordsansible
shouldn't that be: ararecordsansible
```

**Comment by Thulium-Drake** [comment]
> Sweet! I will look into this further tomorrow and try to update my playbooks to use the collection instead of the git checkout I have now. TBC!

I have updated my playbooks and it works like a charm:

* Add to ARA deploy playbook
```
collections:
  - 'arecordsansible.ara'
```

* Add to requirements.yml
```
collections:
  - name: arecordsansible.ara
```

* Install with ansible-galaxy
* Run playbook
* ???
* Profit!
```

**Comment by dmsimard** [comment]
> Hmm, is it me or is there a typo in the namespace?
> 
> ```
> current on galaxy: arecordsansible
> shouldn't that be: ararecordsansible
> ```

I tested with "arecordsansible" because that's the user under which it was published: https://github.com/arecordsansible

I initially wanted to put the collection under ansible community but it's a bit of a convoluted process with a lot of general purpose automation built around it with Zuul -- nothing wrong with that but it's not OpenDev's Zuul (the one that we use for code review), it's Ansible's Zuul.

I'd rather not get in the weeds of using two Zuuls at the same time right now -- or decide whether we should use one or the other. Let's leave that for... later.

Otherwise I'm not a fan of how many collections are like "name.name" (same thing twice!) so I'm leaning towards requesting a "recordsansible" namespace on galaxy which matches the domain (recordsansible.org) and we already have the github org (although it's only used for archival purposes): https://github.com/recordsansible

So the collection would be actually be released under "recordsansible.ara".

**Comment by Thulium-Drake** [comment]
I agree, double the effort _and_ the trouble, best to steer clear of that! :-)

recordsansible.ara sounds like a good plan, also makes sense in the whole naming scheme. But not sure how you'd integrate that with all the code in the current github org..

Maybe better to create a new issue for this on the tracker? As there is a collection which is ready to use and works.

**Comment by dmsimard** [comment]
@Thulium-Drake yeah it would be nice to close this issue so we can move on :)

I've gone ahead and created a request for the namespace here: https://github.com/ansible/galaxy/issues/2440

Once the collection is published under the new namespace I'll consider this done.

**Comment by dmsimard** [comment]
And done :tada: 

https://galaxy.ansible.com/recordsansible/ara

![Screenshot from 2020-07-16 13-19-40](https://user-images.githubusercontent.com/1291204/87702354-4c119100-c767-11ea-804c-c9ad90402fee.png)

I'll advertise this more broadly when I have time.

Thanks everyone for your help on this issue :heart:
