### ISSUE TITLE
No suitable health check target when running with ARA_READ_LOGIN_REQUIRED

### ISSUE THREAD

**Issue by zxaos** [ansible-community/ara#74]
## What component is this about ?
API

## What is your ARA installation like ?
* Ara installed from PyPi
* Wrapped in a container
* Running in k8s

## What is the idea ?
* K8S health checks, and more specifically some ingress load balancers _require_ an unauthenticated http health check that will server a 200. When ara is running in read-login-required mode, there is no suitable endpoint, and thus the container is never deemed "healthy".

It would be helpful to integrate https://github.com/KristianOellegaard/django-health-check , which could provide a basic database-aware unauthenticated healthcheck.

**Comment by zxaos** [comment]
https://review.opendev.org/#/c/687352/

**Comment by dmsimard** [comment]
@zxaos many thanks for the issue AND for taking the time to send a patch !

I've tested it and it works after running a small sql migration. We can mention it in the release notes.
I could also see this being mentioned in the docs somewhere so people know it exists but it doesn't feel like there's any one place that would be appropriate right now.
We need more docs about operating ara in general so I'll create an issue for that.

**Comment by dmsimard** [comment]
https://review.opendev.org/#/c/687352/ is merged :tada:

It'll be in 1.2.0 which is due soon.
