### ISSUE TITLE
Support CORS_ORIGIN_REGEX_WHITELIST

### ISSUE THREAD

**Issue by zxaos** [ansible-community/ara#75]
## What component is this about ?
API

## What is your ARA installation like ?
* Ara installed from PyPi
* Wrapped in a container
* Running in k8s
* [ara-web](https://github.com/ansible-community/ara-web) deployed to [Netlify](https://www.netlify.com)

## What is the idea ?
Supporting django's `CORS_ORIGIN_REGEX_WHITELIST` attribute would be useful for testing ara-web deployments in staging environments.

Background: while testing out ara-web, we used the deployment preview functionality at netlify. This created several ara-web deployments with unique but predictable urls. Having to individually allow each url was really frustrating, so we eventually just modified ara server during our docker build step to enable regex rules for CORS. It would be great to officially support that in ara.

**Comment by dmsimard** [comment]
I don't see a a problem with supporting ``CORS_ORIGIN_REGEX_WHITELIST``, it's just not exposed right now.
The default is an empty list according to [django-cors-headers](https://github.com/adamchainz/django-cors-headers#cors_origin_regex_whitelist) -- I think that's fine.

There are a few places to think about when exposing a new setting:
- settings.py:
https://github.com/ansible-community/ara/blob/034d73a4bd7e165dbce810c4cc1874a2bab77d70/ara/server/settings.py#L72-L73
- https://github.com/ansible-community/ara/blob/034d73a4bd7e165dbce810c4cc1874a2bab77d70/ara/server/settings.py#L245-L246

The ara_api role:
- https://github.com/ansible-community/ara/blob/034d73a4bd7e165dbce810c4cc1874a2bab77d70/roles/ara_api/defaults/main.yaml#L135-L145
- https://github.com/ansible-community/ara/blob/034d73a4bd7e165dbce810c4cc1874a2bab77d70/roles/ara_api/tasks/config.yaml#L71-L99

and finally the docs:
- https://github.com/ansible-community/ara/blob/master/doc/source/api-configuration.rst#overview

**Comment by zxaos** [comment]
- https://review.opendev.org/#/c/687380/
- https://review.opendev.org/#/c/687381/

**Comment by zxaos** [comment]
Oh, oops, didn't consider the ansible task. I'll add it in shortly

**Comment by zxaos** [comment]
https://review.opendev.org/#/c/687380/ updated with role changes and also pulling in the doc changes as one commit

**Comment by dmsimard** [comment]
> https://review.opendev.org/#/c/687380/ updated with role changes and also pulling in the doc changes as one commit

I rebased the patch on top of master and left a comment about a typo.

You can pick up the rebased version by either doing ``git review -d 687380`` or by using the checkout link at the top right of the "download" tab of the patch in gerrit: ``git fetch https://review.opendev.org/recordsansible/ara refs/changes/80/687380/3 && git checkout FETCH_HEAD``.

**Comment by dmsimard** [comment]
Patch has merged and will be in the next release. Thanks for your help !
