### ISSUE TITLE
Slack invatation link is expired

### ISSUE THREAD

**Issue by markfaine** [ansible-community/ara#89]
Slack: https://arecordsansible.slack.com ([invitation link)](https://arecordsansible.slack.com/join/shared_invite/enQtMjMxNzI4ODAxMDQxLWU4MmZhZTI4ZjRjOTUwZTM2MzM3MzcwNDU1YzFmNzRlMzI0NTUzNDY1MWJlNThhM2I4ZTViZjUwZTRkNTBiM2I)

**Comment by dmsimard** [comment]
Thanks ! I've added a new link in https://review.opendev.org/#/c/692816/ and https://review.opendev.org/#/c/692817/.

**Comment by dmsimard** [comment]
This is fixed in both the README and the website.
