### ISSUE TITLE
Labels should wrap

### ISSUE THREAD

**Issue by markfaine** [ansible-community/ara#91]
## What component is this about ?

API Client

## What is your ARA installation like ?

Alpine Docker container in a python virtual environment using git master
The database driver is mysqldb

## What is the idea ?

![image](https://user-images.githubusercontent.com/949949/68139188-564c7180-feef-11e9-841c-8c2ac33f3e2c.png)
See the attached images.  If you have more than a few labels they run over the text.  I think they should probably wrap to a new line, though any solution that looks good is fine.

**Comment by dmsimard** [comment]
@markfaine thanks for the report!

For clarification, this /looks/ like ara-web but I think we have the same issue in the built-in interface.
Fixing it for both would be nice.

**Comment by dmsimard** [comment]
The labels don't wrap in the built-in ARA API interface but I'm not excited about the way it currently looks when there's a lot of labels like this:
![Screenshot from 2020-01-17 17-44-57](https://user-images.githubusercontent.com/1291204/72651397-3c98c300-3951-11ea-9f59-135a3d69baf4.png)

How or where should we display playbook labels ? The intent is for labels to make playbooks easy to search for.

**Comment by dmsimard** [comment]
@markfaine I've found an approach that isn't perfect yet but is much better than the current implementation:

![Screenshot from 2020-01-28 12-14-53](https://user-images.githubusercontent.com/1291204/73287860-edac2280-41c7-11ea-8dce-362a463924f1.png)

The labels are now on a different row and can span the entire width of the playbook card.
Labels have a character limit until they are truncated with an ellipsis but the full label is displayed on mouse-over.

The intent is that clicking on the search icon for a label would search for playbooks matching that label.

The change will land in this [patch](https://review.opendev.org/#/c/704637/) and will be included in the next release of ARA.

**Comment by dmsimard** [comment]
The patch merged in master and will be released in ARA 1.4.

**Comment by markfaine** [comment]
It looks good. Eager to check it out soon. Thanks.
