### ISSUE TITLE
Globally available objects

### ISSUE THREAD

**Issue by markfaine** [ansible-community/ara#93]
## What component is this about ?

API

## What is your ARA installation like ?

Alpine Docker container in a python virtual environment using git master
The database driver is mysqldb

## What is the idea ?

Most, if not all of our projects will be selecting from the same group of inventory, environments, repositories, and keys, it would be nice if there were a way to flag these items as global so that they could be used in any project without recreating them.

**Comment by dmsimard** [comment]
@markfaine could you please give an example of what you mean ? What is being re-created that shouldn't be ? Thanks !

**Comment by dmsimard** [comment]
Hi @markfaine, still waiting for more information on your issue. Thanks.

**Comment by markfaine** [comment]
Sorry, yes, I mean objects such as keys, environments, repositories, that are shared across users in such a way that it doesn't matter who is logged in, or what project they are working on, they can select those resources for in task template.  Does that make sense?

**Comment by dmsimard** [comment]
@markfaine I'm confused because ara doesn't have the concept of projects, keys, repositories or task templates. It sounds like you might be talking about [AWX](https://github.com/ansible/awx) or Tower ?

**Comment by markfaine** [comment]
Yes, :) You are correct sir, sorry to have wasted your time.  It looks like I submitted this feature request on the wrong project.  I will close it now.  Thank you.

**Comment by dmsimard** [comment]
@markfaine no problem! Thanks for clarifying :)
